import type { LessonSeed } from "./types";

export const A1: LessonSeed[] = [
  {
    slug: "colours-clothing", level: "A1", title: "Colours & Clothing", de: "Farben & Kleidung", theme: "everyday",
    summary: "Name colours and clothes and describe what people are wearing.",
    dlg: { title: "Im Kleidergeschäft", lines: [
      ["Verkäufer", "Guten Tag, suchen Sie etwas Bestimmtes?", "Hello, are you looking for something particular?"],
      ["Kundin", "Ja, ich suche eine blaue Jacke.", "Yes, I am looking for a blue jacket."],
      ["Verkäufer", "Welche Größe haben Sie?", "What size are you?"],
      ["Kundin", "Größe achtunddreißig, bitte.", "Size thirty-eight, please."]],
      q: "What is the customer looking for?", opts: ["A blue jacket", "Red shoes", "A green shirt"], a: 0,
      note: "Colour adjectives before a noun take an ending: eine blaue Jacke." },
    read: { title: "Mein Lieblingspullover", de: "Mein Lieblingspullover ist grau und sehr warm. Dazu trage ich oft eine schwarze Hose. Im Sommer trage ich lieber ein weißes T-Shirt.",
      en: "My favourite jumper is grey and very warm. With it I often wear black trousers. In summer I prefer a white T-shirt.",
      q: "What colour is the jumper?", opts: ["Black", "Grey", "White"], a: 1,
      note: "tragen is the verb for wearing clothes." },
    pron: { de: "Ich trage eine rote Jacke.", en: "I am wearing a red jacket.", stress: "ich TRA-ge EI-ne RO-te YA-cke", tip: "The German j in Jacke sounds like the English y." },
    blanks: [
      { s: "Ich möchte ___ blaues Hemd.", en: "I would like a blue shirt.", opts: ["ein", "eine", "einen"], a: 0, note: "das Hemd is neuter, so ein blaues Hemd." },
      { s: "Die Schuhe sind ___.", en: "The shoes are black.", opts: ["schwarz", "schwarze", "schwarzen"], a: 0, note: "After sein the adjective takes no ending." }],
    order: { answer: ["Sie", "trägt", "einen", "grünen", "Mantel"], en: "She is wearing a green coat.", note: "Masculine accusative: einen grünen Mantel." },
    vocab: [["die Jacke", "the jacket"], ["die Hose", "the trousers"], ["rot", "red"], ["gelb", "yellow"]],
    prag: { scenario: "A shop assistant asks if you need help but you just want to browse.", q: "What do you say?", opts: ["Nein.", "Danke, ich schaue mich nur um.", "Lassen Sie mich."], a: 1, note: "Ich schaue mich nur um is the standard polite phrase." },
    write: { prompt: "Was tragen Sie heute? Schreiben Sie drei Sätze.", hint: "Use: Ich trage …, Dazu …, Meine Lieblingsfarbe ist …", sample: "Ich trage heute eine blaue Hose und ein weißes Hemd. Dazu trage ich schwarze Schuhe. Meine Lieblingsfarbe ist grün." },
  },
  {
    slug: "shopping", level: "A1", title: "Shopping & Prices", de: "Einkaufen & Preise", theme: "everyday",
    summary: "Ask for prices, quantities and pay at the checkout.",
    dlg: { title: "An der Kasse", lines: [
      ["Kassiererin", "Das macht zwölf Euro fünfzig.", "That comes to twelve euros fifty."],
      ["Kunde", "Kann ich mit Karte zahlen?", "Can I pay by card?"],
      ["Kassiererin", "Ja, gern. Brauchen Sie eine Tüte?", "Yes, of course. Do you need a bag?"],
      ["Kunde", "Nein danke, ich habe eine Tasche.", "No thanks, I have a bag."]],
      q: "How much does it cost?", opts: ["12.15", "12.50", "20.50"], a: 1,
      note: "Das macht … is how cashiers announce the total." },
    read: { title: "Im Supermarkt", de: "Am Samstag kaufe ich im Supermarkt ein. Ich brauche Milch, Brot und Obst. Das Gemüse ist heute im Angebot.",
      en: "On Saturday I shop in the supermarket. I need milk, bread and fruit. The vegetables are on offer today.",
      q: "What is on offer?", opts: ["Bread", "Vegetables", "Milk"], a: 1,
      note: "im Angebot means on special offer." },
    pron: { de: "Was kostet das, bitte?", en: "What does that cost, please?", stress: "was KOS-tet das BI-tte", tip: "The s in kostet is sharp; keep bitte short and even." },
    blanks: [
      { s: "___ kostet ein Kilo Äpfel?", en: "How much is a kilo of apples?", opts: ["Was", "Wer", "Wo"], a: 0, note: "Was kostet …? asks for a price." },
      { s: "Ich hätte gern ___ Liter Milch.", en: "I would like one litre of milk.", opts: ["einen", "ein", "eine"], a: 1, note: "der Liter is masculine but here it is the accusative measure: einen Liter is also common; ein Liter Milch works as a quantity." }],
    order: { answer: ["Ich", "möchte", "bitte", "zwei", "Brötchen"], en: "I would like two bread rolls, please.", note: "bitte usually sits in the middle of the sentence." },
    vocab: [["die Kasse", "the checkout"], ["das Angebot", "the offer"], ["billig", "cheap"], ["teuer", "expensive"]],
    prag: { scenario: "The cashier says a total you did not understand.", q: "What do you say?", opts: ["Was?", "Entschuldigung, wie viel bitte?", "Nochmal!"], a: 1, note: "Entschuldigung softens a request to repeat." },
    write: { prompt: "Was kaufen Sie jede Woche ein? Drei Sätze.", hint: "Use: Ich kaufe …, Ich brauche …, … ist teuer/billig.", sample: "Ich kaufe jede Woche Brot und Käse. Ich brauche auch Kaffee und Obst. Fleisch ist bei uns ziemlich teuer." },
  },
  {
    slug: "bakery-cafe", level: "A1", title: "At the Bakery & Café", de: "Bäckerei & Café", theme: "food",
    summary: "Order rolls, cake and coffee like a local.",
    dlg: { title: "In der Bäckerei", lines: [
      ["Bäckerin", "Was darf es sein?", "What can I get you?"],
      ["Gast", "Drei Brötchen und ein Stück Kuchen, bitte.", "Three rolls and a piece of cake, please."],
      ["Bäckerin", "Sonst noch etwas?", "Anything else?"],
      ["Gast", "Nein, das ist alles.", "No, that is all."]],
      q: "What does the guest order?", opts: ["Rolls and cake", "Bread and coffee", "Only cake"], a: 0,
      note: "Was darf es sein? is the classic bakery greeting." },
    read: { title: "Kaffee und Kuchen", de: "Am Sonntagnachmittag gibt es bei uns Kaffee und Kuchen. Meine Oma backt einen Apfelkuchen. Wir sitzen lange am Tisch und reden.",
      en: "On Sunday afternoon we have coffee and cake. My grandma bakes an apple cake. We sit at the table for a long time and talk.",
      q: "Who bakes the cake?", opts: ["Mother", "Grandma", "Uncle"], a: 1,
      note: "Kaffee und Kuchen is a German Sunday tradition." },
    pron: { de: "Ein Stück Kuchen, bitte.", en: "A piece of cake, please.", stress: "ein SCHTÜCK KU-chen BI-tte", tip: "st at the start of a word sounds like scht." },
    blanks: [
      { s: "Ich nehme ___ Kaffee.", en: "I will take a coffee.", opts: ["ein", "einen", "eine"], a: 1, note: "der Kaffee is masculine, accusative einen." },
      { s: "___ noch etwas?", en: "Anything else?", opts: ["Sonst", "Immer", "Auch"], a: 0, note: "Sonst noch etwas? is the fixed phrase." }],
    order: { answer: ["Ich", "hätte", "gern", "zwei", "Stück", "Kuchen"], en: "I would like two pieces of cake.", note: "Stück stays singular after numbers." },
    vocab: [["das Brötchen", "the bread roll"], ["der Kuchen", "the cake"], ["die Sahne", "the cream"], ["zum Mitnehmen", "to take away"]],
    prag: { scenario: "You want your coffee to take away.", q: "How do you say it?", opts: ["Kaffee, weg!", "Einen Kaffee zum Mitnehmen, bitte.", "Kaffee gehen."], a: 1, note: "zum Mitnehmen is the standard phrase for takeaway." },
    write: { prompt: "Bestellen Sie schriftlich in einem Café. Drei Sätze.", hint: "Use: Ich hätte gern …, Und dazu …, Zahlen bitte.", sample: "Ich hätte gern einen Tee mit Zitrone. Und dazu ein Stück Apfelkuchen, bitte. Zahlen bitte, mit Karte." },
  },
  {
    slug: "weather", level: "A1", title: "Weather & Seasons", de: "Wetter & Jahreszeiten", theme: "smalltalk",
    summary: "Describe the weather and the seasons in simple sentences.",
    dlg: { title: "Wie ist das Wetter?", lines: [
      ["Ali", "Wie ist das Wetter heute?", "What is the weather like today?"],
      ["Mia", "Es ist kalt und es regnet.", "It is cold and it is raining."],
      ["Ali", "Und morgen?", "And tomorrow?"],
      ["Mia", "Morgen wird es sonnig.", "Tomorrow it will be sunny."]],
      q: "What is the weather today?", opts: ["Sunny", "Cold and rainy", "Snowy"], a: 1,
      note: "Weather sentences start with the impersonal es." },
    read: { title: "Die Jahreszeiten", de: "Im Frühling wird es wärmer und die Blumen blühen. Der Sommer ist heiß. Im Herbst regnet es oft, und im Winter schneit es manchmal.",
      en: "In spring it gets warmer and the flowers bloom. Summer is hot. In autumn it often rains, and in winter it sometimes snows.",
      q: "When does it snow?", opts: ["In winter", "In spring", "In autumn"], a: 0,
      note: "Seasons take im: im Frühling, im Sommer." },
    pron: { de: "Heute scheint die Sonne.", en: "The sun is shining today.", stress: "HEU-te SCHEINT die SO-nne", tip: "eu sounds like oy; sch is a single sh sound." },
    blanks: [
      { s: "Es ___ heute stark.", en: "It is raining heavily today.", opts: ["regnet", "regnen", "geregnet"], a: 0, note: "es takes the third person singular regnet." },
      { s: "___ Winter ist es kalt.", en: "In winter it is cold.", opts: ["In", "Im", "Am"], a: 1, note: "Seasons use im." }],
    order: { answer: ["Morgen", "wird", "es", "warm", "und", "sonnig"], en: "Tomorrow it will be warm and sunny.", note: "Time word first, verb second." },
    vocab: [["der Regen", "the rain"], ["der Schnee", "the snow"], ["bewölkt", "cloudy"], ["windig", "windy"]],
    prag: { scenario: "You want to start small talk with a neighbour at the bus stop.", q: "What is a natural opener?", opts: ["Sie sehen müde aus.", "Ganz schön kalt heute, oder?", "Wie viel verdienen Sie?"], a: 1, note: "Weather is the safest small talk topic in Germany." },
    write: { prompt: "Wie ist das Wetter bei Ihnen? Drei Sätze.", hint: "Use: Heute ist es …, Im Sommer …, Ich mag … Wetter.", sample: "Heute ist es bewölkt und windig. Im Sommer wird es hier sehr heiß. Ich mag sonniges Wetter am liebsten." },
  },
  {
    slug: "days-months", level: "A1", title: "Days, Months & Dates", de: "Tage, Monate & Datum", theme: "time",
    summary: "Say dates, birthdays and days of the week.",
    dlg: { title: "Wann hast du Geburtstag?", lines: [
      ["Emma", "Wann hast du Geburtstag?", "When is your birthday?"],
      ["Nils", "Am dritten Mai. Und du?", "On the third of May. And you?"],
      ["Emma", "Im Dezember, am zwanzigsten.", "In December, on the twentieth."]],
      q: "When is Nils's birthday?", opts: ["3 May", "20 December", "13 March"], a: 0,
      note: "Dates use am plus an ordinal number." },
    read: { title: "Mein Wochenplan", de: "Am Montag arbeite ich lange. Am Mittwoch gehe ich zum Deutschkurs. Am Wochenende besuche ich meine Familie.",
      en: "On Monday I work long hours. On Wednesday I go to the German course. At the weekend I visit my family.",
      q: "When is the German course?", opts: ["Monday", "Wednesday", "Sunday"], a: 1,
      note: "Days of the week take am." },
    pron: { de: "Am Dienstag habe ich Zeit.", en: "On Tuesday I have time.", stress: "am DIENS-tag HA-be ich TSEIT", tip: "The z in Zeit is a ts sound." },
    blanks: [
      { s: "___ Freitag gehe ich ins Kino.", en: "On Friday I go to the cinema.", opts: ["Am", "Im", "An"], a: 0, note: "Days take am." },
      { s: "Ich habe ___ Juli Urlaub.", en: "I have holiday in July.", opts: ["am", "im", "um"], a: 1, note: "Months take im." }],
    order: { answer: ["Mein", "Kurs", "beginnt", "am", "ersten", "September"], en: "My course starts on the first of September.", note: "am + ordinal + month for dates." },
    vocab: [["der Montag", "Monday"], ["der Monat", "the month"], ["das Datum", "the date"], ["das Wochenende", "the weekend"]],
    prag: { scenario: "You must give your date of birth on the phone to an office.", q: "What is clearest?", opts: ["Mai drei.", "Ich bin am dritten Mai neunzehnhundertneunzig geboren.", "Dreißig fünf."], a: 1, note: "Full sentences avoid misunderstandings on the phone." },
    write: { prompt: "Beschreiben Sie Ihre Woche. Drei Sätze mit Tagen.", hint: "Use: Am Montag …, Am Donnerstag …, Am Wochenende …", sample: "Am Montag arbeite ich von acht bis fünf. Am Donnerstag gehe ich zum Sport. Am Wochenende koche ich mit Freunden." },
  },
  {
    slug: "hobbies", level: "A1", title: "Hobbies & Free Time", de: "Hobbys & Freizeit", theme: "leisure",
    summary: "Say what you like doing with gern and your free time.",
    dlg: { title: "Was machst du gern?", lines: [
      ["Ana", "Was machst du gern in deiner Freizeit?", "What do you like doing in your free time?"],
      ["Timo", "Ich spiele gern Fußball und lese viel.", "I like playing football and read a lot."],
      ["Ana", "Ich tanze lieber.", "I prefer dancing."]],
      q: "What does Timo like?", opts: ["Dancing", "Football and reading", "Cooking"], a: 1,
      note: "gern after the verb expresses liking an activity." },
    read: { title: "Meine Freizeit", de: "Nach der Arbeit gehe ich oft schwimmen. Am Wochenende treffe ich Freunde oder höre Musik. Manchmal fahre ich mit dem Rad ins Grüne.",
      en: "After work I often go swimming. At the weekend I meet friends or listen to music. Sometimes I cycle out into the countryside.",
      q: "What does the writer do after work?", opts: ["Swim", "Cook", "Study"], a: 0,
      note: "gehen + infinitive: schwimmen gehen." },
    pron: { de: "Ich höre gern Musik.", en: "I like listening to music.", stress: "ich HÖ-re gern mu-SIK", tip: "ö is rounded; Musik stresses the second syllable." },
    blanks: [
      { s: "Ich spiele ___ Gitarre.", en: "I like playing the guitar.", opts: ["gern", "gut", "viel"], a: 0, note: "gern expresses enjoyment." },
      { s: "Am liebsten ___ ich ins Kino.", en: "Most of all I go to the cinema.", opts: ["gehe", "gehen", "geht"], a: 0, note: "The verb comes second after am liebsten." }],
    order: { answer: ["Am", "Wochenende", "spiele", "ich", "gern", "Tennis"], en: "At the weekend I like playing tennis.", note: "Time phrase first, verb second." },
    vocab: [["die Freizeit", "the free time"], ["das Hobby", "the hobby"], ["malen", "to paint"], ["wandern", "to hike"]],
    prag: { scenario: "A new classmate asks about your hobbies.", q: "Which answer keeps the conversation going?", opts: ["Nichts.", "Ich koche gern. Und du?", "Frag nicht."], a: 1, note: "Answer plus a return question builds rapport." },
    write: { prompt: "Was machen Sie gern in der Freizeit? Drei Sätze.", hint: "Use: Ich … gern, Manchmal …, Am liebsten …", sample: "Ich lese gern Krimis. Manchmal gehe ich mit Freunden ins Schwimmbad. Am liebsten koche ich am Wochenende." },
  },
  {
    slug: "home-rooms", level: "A1", title: "My Home", de: "Meine Wohnung", theme: "home",
    summary: "Describe rooms and where you live.",
    dlg: { title: "Deine neue Wohnung", lines: [
      ["Jana", "Wie ist deine neue Wohnung?", "What is your new flat like?"],
      ["Omar", "Klein, aber hell. Sie hat zwei Zimmer.", "Small but bright. It has two rooms."],
      ["Jana", "Und wo liegt sie?", "And where is it?"],
      ["Omar", "Im Zentrum, neben dem Park.", "In the centre, next to the park."]],
      q: "Where is the flat?", opts: ["In the centre", "Outside town", "By the station"], a: 0,
      note: "liegen is used for the position of buildings and places." },
    read: { title: "Zu Hause", de: "Unsere Wohnung hat drei Zimmer, eine Küche und ein Bad. Das Wohnzimmer ist groß und hell. Mein Zimmer ist klein, aber gemütlich.",
      en: "Our flat has three rooms, a kitchen and a bathroom. The living room is big and bright. My room is small but cosy.",
      q: "How is the living room?", opts: ["Small", "Big and bright", "Dark"], a: 1,
      note: "aber links two contrasting adjectives." },
    pron: { de: "Die Küche ist sehr klein.", en: "The kitchen is very small.", stress: "die KÜ-che ist sehr KLEIN", tip: "ü is rounded; the ch after ü is the soft ich-Laut." },
    blanks: [
      { s: "Ich wohne ___ einer Wohnung.", en: "I live in a flat.", opts: ["in", "an", "auf"], a: 0, note: "wohnen in + dative." },
      { s: "Das Bad ist ___ Küche.", en: "The bathroom is next to the kitchen.", opts: ["neben der", "neben die", "neben"], a: 0, note: "Position takes the dative: neben der Küche." }],
    order: { answer: ["Meine", "Wohnung", "hat", "einen", "Balkon"], en: "My flat has a balcony.", note: "haben takes the accusative: einen Balkon." },
    vocab: [["das Zimmer", "the room"], ["die Küche", "the kitchen"], ["der Flur", "the hallway"], ["gemütlich", "cosy"]],
    prag: { scenario: "A guest visits your home for the first time.", q: "What do you say at the door?", opts: ["Komm rein, herzlich willkommen!", "Schuhe aus, sofort.", "Was willst du?"], a: 0, note: "A warm welcome first; you can mention shoes afterwards." },
    write: { prompt: "Beschreiben Sie Ihre Wohnung. Drei Sätze.", hint: "Use: Meine Wohnung hat …, Das … ist …, Ich wohne …", sample: "Meine Wohnung hat zwei Zimmer und eine kleine Küche. Das Wohnzimmer ist hell und gemütlich. Ich wohne im dritten Stock." },
  },
  {
    slug: "furniture", level: "A1", title: "Furniture & Prepositions", de: "Möbel & Präpositionen", theme: "home",
    summary: "Say where furniture stands with auf, unter and neben.",
    dlg: { title: "Wo ist mein Handy?", lines: [
      ["Lukas", "Wo ist mein Handy?", "Where is my phone?"],
      ["Sara", "Es liegt auf dem Tisch.", "It is lying on the table."],
      ["Lukas", "Und meine Schlüssel?", "And my keys?"],
      ["Sara", "Die sind in der Schublade.", "They are in the drawer."]],
      q: "Where is the phone?", opts: ["In the drawer", "On the table", "Under the sofa"], a: 1,
      note: "liegen for flat objects, stehen for upright ones." },
    read: { title: "Mein Zimmer", de: "Mein Bett steht am Fenster. Neben dem Bett steht ein kleiner Schrank. Unter dem Schreibtisch liegt ein Teppich.",
      en: "My bed stands by the window. Next to the bed is a small cupboard. Under the desk lies a rug.",
      q: "What is under the desk?", opts: ["A rug", "A chair", "A box"], a: 0,
      note: "Positions always take the dative." },
    pron: { de: "Der Stuhl steht neben dem Tisch.", en: "The chair is next to the table.", stress: "der SCHTUHL schteht NE-ben dem TISCH", tip: "st at the start of a word is scht." },
    blanks: [
      { s: "Die Lampe steht ___ Schreibtisch.", en: "The lamp is on the desk.", opts: ["auf dem", "auf den", "auf der"], a: 0, note: "Position: auf + dative." },
      { s: "Die Katze schläft ___ Sofa.", en: "The cat sleeps under the sofa.", opts: ["unter dem", "unter das", "unter der"], a: 0, note: "das Sofa becomes dem Sofa in the dative." }],
    order: { answer: ["Der", "Fernseher", "steht", "in", "der", "Ecke"], en: "The television is in the corner.", note: "stehen with a dative place phrase." },
    vocab: [["der Schrank", "the cupboard"], ["das Regal", "the shelf"], ["der Sessel", "the armchair"], ["der Teppich", "the rug"]],
    prag: { scenario: "You are helping a friend move furniture.", q: "Which sentence is helpful and polite?", opts: ["Mach schneller.", "Soll der Schrank neben das Fenster?", "Ist mir egal."], a: 1, note: "A question checks the plan before heavy lifting." },
    write: { prompt: "Wo stehen die Möbel in Ihrem Zimmer? Drei Sätze.", hint: "Use: … steht …, Neben dem …, Unter dem …", sample: "Mein Bett steht neben der Tür. Neben dem Bett steht ein kleines Regal. Unter dem Fenster steht ein Schreibtisch." },
  },
  {
    slug: "jobs", level: "A1", title: "Jobs & Professions", de: "Berufe", theme: "work",
    summary: "Say what you do for a living and where you work.",
    dlg: { title: "Was machen Sie beruflich?", lines: [
      ["Frau Roth", "Was machen Sie beruflich?", "What do you do for a living?"],
      ["Herr Diaz", "Ich bin Krankenpfleger im Krankenhaus.", "I am a nurse at the hospital."],
      ["Frau Roth", "Und arbeiten Sie Vollzeit?", "And do you work full time?"],
      ["Herr Diaz", "Nein, dreißig Stunden pro Woche.", "No, thirty hours a week."]],
      q: "Where does Herr Diaz work?", opts: ["In a school", "In a hospital", "In an office"], a: 1,
      note: "Professions take no article: Ich bin Krankenpfleger." },
    read: { title: "Berufe in meiner Familie", de: "Meine Mutter ist Lehrerin an einer Grundschule. Mein Vater arbeitet als Techniker bei einer Firma. Meine Schwester studiert noch.",
      en: "My mother is a teacher at a primary school. My father works as a technician at a company. My sister is still studying.",
      q: "What does the father do?", opts: ["Teacher", "Technician", "Student"], a: 1,
      note: "arbeiten als + profession without an article." },
    pron: { de: "Ich arbeite als Verkäuferin.", en: "I work as a sales assistant.", stress: "ich AR-bei-te als fer-KÄU-fe-rin", tip: "The v in Verkäuferin sounds like f; äu sounds like oy." },
    blanks: [
      { s: "Ich bin ___ Beruf Köchin.", en: "I am a cook by profession.", opts: ["von", "in", "als"], a: 0, note: "The fixed phrase is von Beruf." },
      { s: "Er arbeitet ___ einer Bank.", en: "He works at a bank.", opts: ["bei", "in", "an"], a: 0, note: "bei + employer, in + building." }],
    order: { answer: ["Ich", "arbeite", "seit", "zwei", "Jahren", "hier"], en: "I have been working here for two years.", note: "seit + dative with the present tense." },
    vocab: [["der Beruf", "the profession"], ["die Firma", "the company"], ["die Stelle", "the position"], ["die Kollegin", "the colleague"]],
    prag: { scenario: "At a party a stranger asks what you do.", q: "Which reply is natural in German?", opts: ["Ich bin Ingenieurin, und Sie?", "Ich verdiene gut.", "Warum fragen Sie?"], a: 0, note: "State the job briefly and return the question." },
    write: { prompt: "Beschreiben Sie Ihren Beruf oder Ihren Wunschberuf. Drei Sätze.", hint: "Use: Ich bin …, Ich arbeite bei/in …, Meine Arbeit ist …", sample: "Ich bin Programmiererin von Beruf. Ich arbeite bei einer kleinen Firma in Köln. Meine Arbeit ist anstrengend, aber interessant." },
  },
  {
    slug: "school-course", level: "A1", title: "School & Language Course", de: "Schule & Sprachkurs", theme: "learning",
    summary: "Handle classroom language and talk about learning German.",
    dlg: { title: "Im Deutschkurs", lines: [
      ["Lehrerin", "Haben Sie eine Frage?", "Do you have a question?"],
      ["Teilnehmer", "Ja, wie schreibt man das Wort?", "Yes, how do you write that word?"],
      ["Lehrerin", "Ich schreibe es an die Tafel.", "I will write it on the board."],
      ["Teilnehmer", "Danke, jetzt verstehe ich.", "Thanks, now I understand."]],
      q: "What does the participant ask?", opts: ["How to write the word", "The price", "The homework"], a: 0,
      note: "Wie schreibt man …? uses the impersonal man." },
    read: { title: "Mein Kurs", de: "Mein Deutschkurs beginnt um neun Uhr. Wir sind zwölf Teilnehmer aus acht Ländern. Die Hausaufgaben mache ich abends.",
      en: "My German course starts at nine. We are twelve participants from eight countries. I do the homework in the evening.",
      q: "How many participants are there?", opts: ["Eight", "Twelve", "Nine"], a: 1,
      note: "aus + country for origin." },
    pron: { de: "Können Sie das bitte wiederholen?", en: "Can you repeat that, please?", stress: "KÖ-nnen sie das BI-tte wie-der-HO-len", tip: "wiederholen stresses -ho-, not the prefix." },
    blanks: [
      { s: "Wie ___ man das auf Deutsch?", en: "How do you say that in German?", opts: ["sagt", "sagen", "gesagt"], a: 0, note: "man takes the third person singular." },
      { s: "Ich verstehe das Wort ___.", en: "I do not understand the word.", opts: ["nicht", "kein", "nichts"], a: 0, note: "nicht negates a verb; kein negates a noun." }],
    order: { answer: ["Ich", "lerne", "seit", "einem", "Jahr", "Deutsch"], en: "I have been learning German for a year.", note: "seit + dative with the present tense." },
    vocab: [["die Aufgabe", "the task"], ["die Tafel", "the board"], ["das Wort", "the word"], ["üben", "to practise"]],
    prag: { scenario: "The teacher speaks too fast for you.", q: "What do you say?", opts: ["Sie sprechen zu schnell!", "Könnten Sie bitte etwas langsamer sprechen?", "Ich verstehe nichts."], a: 1, note: "A polite request is more effective than criticism." },
    write: { prompt: "Warum lernen Sie Deutsch? Drei Sätze.", hint: "Use: Ich lerne Deutsch, weil …, Mein Kurs …, Ich übe …", sample: "Ich lerne Deutsch, weil ich hier arbeiten möchte. Mein Kurs ist am Abend von sechs bis acht. Ich übe jeden Tag zwanzig Minuten." },
  },
  {
    slug: "body-health", level: "A1", title: "Body & Feeling Unwell", de: "Körper & Beschwerden", theme: "health",
    summary: "Name body parts and say what hurts.",
    dlg: { title: "Was fehlt dir?", lines: [
      ["Ute", "Du siehst müde aus. Was fehlt dir?", "You look tired. What is wrong?"],
      ["Jan", "Mein Kopf tut weh.", "My head hurts."],
      ["Ute", "Trink viel Wasser und ruh dich aus.", "Drink a lot of water and rest."]],
      q: "What is wrong with Jan?", opts: ["Headache", "Stomach ache", "Sore throat"], a: 0,
      note: "… tut weh is the standard way to say something hurts." },
    read: { title: "Erkältet", de: "Ich bin erkältet. Mein Hals tut weh und ich huste viel. Ich trinke Tee mit Honig und bleibe zu Hause.",
      en: "I have a cold. My throat hurts and I cough a lot. I drink tea with honey and stay at home.",
      q: "What does the writer drink?", opts: ["Coffee", "Tea with honey", "Juice"], a: 1,
      note: "erkältet sein means to have a cold." },
    pron: { de: "Mein Rücken tut weh.", en: "My back hurts.", stress: "mein RÜ-cken tut WEH", tip: "ü is rounded; weh has a long open e." },
    blanks: [
      { s: "Meine Augen ___ weh.", en: "My eyes hurt.", opts: ["tun", "tut", "tue"], a: 0, note: "Plural subject takes tun." },
      { s: "Ich habe ___ .", en: "I have a fever.", opts: ["Fieber", "kalt", "krank"], a: 0, note: "Fieber haben is the fixed expression." }],
    order: { answer: ["Ich", "habe", "seit", "gestern", "Halsschmerzen"], en: "I have had a sore throat since yesterday.", note: "seit + dative for a duration up to now." },
    vocab: [["der Kopf", "the head"], ["der Bauch", "the stomach"], ["die Schmerzen", "the pain"], ["die Erkältung", "the cold"]],
    prag: { scenario: "You are too ill to come to work.", q: "What do you tell your manager?", opts: ["Komme nicht.", "Ich bin krank und gehe heute zum Arzt. Ich melde mich am Nachmittag.", "Bin heute weg."], a: 1, note: "State the reason and promise an update." },
    write: { prompt: "Sie sind krank. Schreiben Sie eine kurze Nachricht.", hint: "Use: Ich bin …, Ich habe …, Ich hoffe …", sample: "Hallo Frau Bauer, ich bin heute krank. Ich habe Fieber und Halsschmerzen. Ich hoffe, dass ich morgen wieder da bin." },
  },
  {
    slug: "doctor", level: "A1", title: "At the Doctor", de: "Beim Arzt", theme: "health",
    summary: "Make an appointment and describe symptoms at the practice.",
    dlg: { title: "In der Praxis", lines: [
      ["Sprechstundenhilfe", "Haben Sie einen Termin?", "Do you have an appointment?"],
      ["Patientin", "Nein, aber ich habe starke Schmerzen.", "No, but I am in a lot of pain."],
      ["Sprechstundenhilfe", "Haben Sie Ihre Versichertenkarte dabei?", "Do you have your insurance card with you?"],
      ["Patientin", "Ja, hier bitte.", "Yes, here you are."]],
      q: "What does the assistant ask for?", opts: ["Insurance card", "Passport", "Payment"], a: 0,
      note: "Die Versichertenkarte is required at every German practice." },
    read: { title: "Die Untersuchung", de: "Der Arzt untersucht mich und misst das Fieber. Er sagt, ich soll drei Tage im Bett bleiben. Er schreibt mir ein Rezept.",
      en: "The doctor examines me and takes my temperature. He says I should stay in bed for three days. He writes me a prescription.",
      q: "What does the doctor recommend?", opts: ["Three days in bed", "Sport", "A trip"], a: 0,
      note: "sollen expresses a recommendation or instruction." },
    pron: { de: "Ich brauche einen Termin beim Arzt.", en: "I need an appointment with the doctor.", stress: "ich BRAU-che EI-nen ter-MIN beim ARTST", tip: "Termin stresses the second syllable; Arzt ends in a tst cluster." },
    blanks: [
      { s: "Ich möchte einen Termin ___.", en: "I would like to make an appointment.", opts: ["vereinbaren", "kaufen", "sagen"], a: 0, note: "einen Termin vereinbaren is the fixed phrase." },
      { s: "Der Arzt ___ mir ein Medikament.", en: "The doctor prescribes me a medicine.", opts: ["verschreibt", "schreibt", "gibt"], a: 0, note: "verschreiben is the medical term for prescribing." }],
    order: { answer: ["Ich", "habe", "seit", "drei", "Tagen", "Fieber"], en: "I have had a fever for three days.", note: "Duration with seit comes before the symptom." },
    vocab: [["die Praxis", "the practice"], ["das Rezept", "the prescription"], ["die Apotheke", "the pharmacy"], ["die Krankschreibung", "the sick note"]],
    prag: { scenario: "You need a sick note for your employer.", q: "How do you ask?", opts: ["Geben Sie mir einen Zettel.", "Könnten Sie mir bitte eine Krankschreibung ausstellen?", "Ich brauche Papier."], a: 1, note: "Use the exact term Krankschreibung with a polite question." },
    write: { prompt: "Rufen Sie schriftlich in einer Praxis an und bitten Sie um einen Termin.", hint: "Use: Guten Tag, ich hätte gern …, Ich habe …, Vielen Dank.", sample: "Guten Tag, ich hätte gern einen Termin in dieser Woche. Ich habe seit drei Tagen starke Kopfschmerzen. Vielen Dank für Ihre Hilfe." },
  },
  {
    slug: "transport", level: "A1", title: "Public Transport", de: "Bus & Bahn", theme: "travel",
    summary: "Buy tickets and understand connections.",
    dlg: { title: "Am Fahrkartenautomat", lines: [
      ["Reisende", "Entschuldigung, wie funktioniert der Automat?", "Excuse me, how does the machine work?"],
      ["Passant", "Zuerst das Ziel wählen, dann bezahlen.", "First select the destination, then pay."],
      ["Reisende", "Und wie viel kostet eine Einzelfahrt?", "And how much is a single ticket?"],
      ["Passant", "Drei Euro zwanzig.", "Three euros twenty."]],
      q: "How much is a single ticket?", opts: ["2.30", "3.20", "3.50"], a: 1,
      note: "zuerst … dann … orders instructions." },
    read: { title: "Mit der U-Bahn", de: "Ich fahre jeden Tag mit der U-Bahn zur Arbeit. Die Fahrt dauert zwanzig Minuten. Manchmal ist der Zug voll.",
      en: "I take the underground to work every day. The journey takes twenty minutes. Sometimes the train is full.",
      q: "How long is the journey?", opts: ["Ten minutes", "Twenty minutes", "An hour"], a: 1,
      note: "mit + dative for means of transport." },
    pron: { de: "Ich fahre mit dem Zug.", en: "I travel by train.", stress: "ich FAH-re mit dem TSUK", tip: "Zug starts with ts and ends with a hard k sound." },
    blanks: [
      { s: "Ich fahre ___ Bus zur Schule.", en: "I go to school by bus.", opts: ["mit dem", "mit der", "in den"], a: 0, note: "der Bus becomes dem Bus in the dative." },
      { s: "Der Zug ___ um zehn Uhr ab.", en: "The train departs at ten.", opts: ["fährt", "fahren", "gefahren"], a: 0, note: "abfahren is separable: fährt … ab." }],
    order: { answer: ["Wann", "fährt", "der", "nächste", "Bus"], en: "When does the next bus leave?", note: "Question word first, verb second." },
    vocab: [["die Fahrkarte", "the ticket"], ["der Bahnsteig", "the platform"], ["umsteigen", "to change trains"], ["die Verspätung", "the delay"]],
    prag: { scenario: "A ticket inspector asks for your ticket but you cannot find it.", q: "What do you say?", opts: ["Ich habe keine.", "Einen Moment bitte, ich suche sie kurz.", "Später."], a: 1, note: "Ask for a moment calmly instead of denying." },
    write: { prompt: "Wie kommen Sie zur Arbeit oder zum Kurs? Drei Sätze.", hint: "Use: Ich fahre mit …, Die Fahrt dauert …, Manchmal …", sample: "Ich fahre mit der Straßenbahn zum Kurs. Die Fahrt dauert eine Viertelstunde. Manchmal gehe ich auch zu Fuß." },
  },
  {
    slug: "train-station", level: "A1", title: "At the Station", de: "Am Bahnhof", theme: "travel",
    summary: "Ask about platforms, connections and delays.",
    dlg: { title: "Auskunft am Schalter", lines: [
      ["Reisender", "Wann fährt der nächste Zug nach Köln?", "When does the next train to Cologne leave?"],
      ["Beamtin", "Um vierzehn Uhr zehn, Gleis sieben.", "At 14:10, platform seven."],
      ["Reisender", "Muss ich umsteigen?", "Do I have to change?"],
      ["Beamtin", "Ja, in Hannover.", "Yes, in Hanover."]],
      q: "Which platform?", opts: ["Seven", "Ten", "Fourteen"], a: 0,
      note: "Gleis plus number for platforms." },
    read: { title: "Die Durchsage", de: "Achtung am Gleis drei: Der Zug nach Berlin hat zehn Minuten Verspätung. Bitte beachten Sie die Anzeigetafel. Wir bitten um Ihr Verständnis.",
      en: "Attention on platform three: the train to Berlin is ten minutes late. Please note the display board. We ask for your understanding.",
      q: "What is the delay?", opts: ["Five minutes", "Ten minutes", "An hour"], a: 1,
      note: "Verspätung haben is the standard phrase for a delay." },
    pron: { de: "Der Zug fährt von Gleis vier ab.", en: "The train departs from platform four.", stress: "der TSUK fährt fon GLEIS FIER ab", tip: "ei sounds like eye; the prefix ab is stressed at the end." },
    blanks: [
      { s: "Der Zug fährt ___ Gleis zwei.", en: "The train leaves from platform two.", opts: ["von", "aus", "an"], a: 0, note: "von + Gleis for departures." },
      { s: "Ich muss in Fulda ___.", en: "I have to change in Fulda.", opts: ["umsteigen", "aussteigen", "einsteigen"], a: 0, note: "umsteigen means to change trains." }],
    order: { answer: ["Wo", "finde", "ich", "die", "Information"], en: "Where do I find the information desk?", note: "Question word first, verb second." },
    vocab: [["das Gleis", "the platform"], ["die Ankunft", "the arrival"], ["die Abfahrt", "the departure"], ["die Anzeigetafel", "the display board"]],
    prag: { scenario: "Your train is cancelled and you must ask for help.", q: "What is the best opening?", opts: ["Das ist eine Frechheit!", "Entschuldigung, mein Zug fällt aus. Welche Verbindung empfehlen Sie?", "Sie sind schuld."], a: 1, note: "State the problem and ask for a recommendation." },
    write: { prompt: "Fragen Sie schriftlich nach einer Zugverbindung.", hint: "Use: Guten Tag, ich möchte …, Wann …, Muss ich …", sample: "Guten Tag, ich möchte am Freitag nach Hamburg fahren. Wann fährt der erste Zug am Morgen? Muss ich unterwegs umsteigen?" },
  },
  {
    slug: "telephone", level: "A1", title: "On the Phone", de: "Am Telefon", theme: "communication",
    summary: "Answer calls, spell names and leave messages.",
    dlg: { title: "Ein Anruf", lines: [
      ["Frau Kern", "Kern, guten Tag.", "Kern speaking, hello."],
      ["Anrufer", "Guten Tag, hier ist Paulo Silva. Kann ich Herrn Weber sprechen?", "Hello, this is Paulo Silva. Can I speak to Mr Weber?"],
      ["Frau Kern", "Er ist gerade in einer Besprechung. Soll er zurückrufen?", "He is in a meeting right now. Shall he call back?"],
      ["Anrufer", "Ja, gern.", "Yes, please."]],
      q: "Where is Mr Weber?", opts: ["On holiday", "In a meeting", "At lunch"], a: 1,
      note: "Germans often answer the phone with just their surname." },
    read: { title: "Die Nachricht", de: "Guten Tag, hier spricht Ana Lima. Ich rufe wegen des Termins am Montag an. Bitte rufen Sie mich unter null eins sieben null zurück.",
      en: "Hello, this is Ana Lima. I am calling about the appointment on Monday. Please call me back on 0170.",
      q: "Why is she calling?", opts: ["About Monday's appointment", "About a bill", "About a job"], a: 0,
      note: "anrufen wegen + genitive/dative explains the reason." },
    pron: { de: "Können Sie das bitte buchstabieren?", en: "Could you spell that, please?", stress: "KÖ-nnen sie das BI-tte buch-schta-BIE-ren", tip: "buchstabieren stresses -bie-; the st inside sounds scht here." },
    blanks: [
      { s: "___ ist Herr Lopez.", en: "This is Mr Lopez speaking.", opts: ["Hier", "Da", "Dort"], a: 0, note: "Hier ist … introduces yourself on the phone." },
      { s: "Ich rufe später ___.", en: "I will call back later.", opts: ["zurück", "an", "auf"], a: 0, note: "zurückrufen is separable." }],
    order: { answer: ["Kann", "ich", "eine", "Nachricht", "hinterlassen"], en: "Can I leave a message?", note: "Modal verb first in a yes/no question." },
    vocab: [["der Anruf", "the call"], ["die Nachricht", "the message"], ["die Durchwahl", "the extension"], ["besetzt", "engaged"]],
    prag: { scenario: "You reach a wrong number.", q: "What do you say?", opts: ["Falsch!", "Entschuldigung, ich habe mich verwählt.", "Wer sind Sie?"], a: 1, note: "sich verwählen is the polite way to admit a wrong number." },
    write: { prompt: "Hinterlassen Sie schriftlich eine Telefonnachricht.", hint: "Use: Guten Tag, hier ist …, Ich rufe wegen … an, Bitte rufen Sie …", sample: "Guten Tag, hier ist Nina Petrova. Ich rufe wegen meines Termins am Mittwoch an. Bitte rufen Sie mich heute Nachmittag zurück." },
  },
  {
    slug: "invitations", level: "A1", title: "Invitations & Plans", de: "Einladungen & Verabredungen", theme: "social",
    summary: "Invite someone, accept and decline politely.",
    dlg: { title: "Hast du Zeit?", lines: [
      ["Lina", "Hast du am Freitag Zeit?", "Do you have time on Friday?"],
      ["Marek", "Ja, warum?", "Yes, why?"],
      ["Lina", "Wir gehen ins Kino. Kommst du mit?", "We are going to the cinema. Are you coming along?"],
      ["Marek", "Gern, um wie viel Uhr?", "Gladly, at what time?"]],
      q: "What is the plan?", opts: ["Cinema", "Dinner", "Football"], a: 0,
      note: "mitkommen is separable: Kommst du mit?" },
    read: { title: "Eine Absage", de: "Danke für die Einladung! Leider kann ich am Samstag nicht. Ich habe schon etwas vor. Vielleicht nächste Woche?",
      en: "Thanks for the invitation! Unfortunately I cannot on Saturday. I already have plans. Maybe next week?",
      q: "Can the writer come?", opts: ["Yes", "No, they have plans", "Only later"], a: 1,
      note: "etwas vorhaben means to have plans." },
    pron: { de: "Hast du Lust, ins Kino zu gehen?", en: "Do you fancy going to the cinema?", stress: "hast du LUST ins KI-no tsu GE-hen", tip: "zu gehen keeps zu unstressed and short." },
    blanks: [
      { s: "Hast du am Sonntag ___?", en: "Do you have time on Sunday?", opts: ["Zeit", "Uhr", "Termin"], a: 0, note: "Zeit haben is the fixed phrase." },
      { s: "Leider kann ich ___.", en: "Unfortunately I cannot.", opts: ["nicht", "kein", "nichts"], a: 0, note: "nicht negates the modal verb." }],
    order: { answer: ["Wollen", "wir", "am", "Samstag", "essen", "gehen"], en: "Shall we go out to eat on Saturday?", note: "Two verbs at the end: essen gehen." },
    vocab: [["die Einladung", "the invitation"], ["absagen", "to cancel"], ["zusagen", "to accept"], ["sich verabreden", "to arrange to meet"]],
    prag: { scenario: "You must decline an invitation from a colleague.", q: "Which refusal keeps the relationship warm?", opts: ["Nein.", "Danke für die Einladung! Diesmal schaffe ich es leider nicht, aber nächstes Mal gern.", "Keine Zeit."], a: 1, note: "Thank, decline, and offer an alternative." },
    write: { prompt: "Laden Sie eine Freundin zum Essen ein.", hint: "Use: Hast du am … Zeit?, Wir könnten …, Sag mir Bescheid.", sample: "Hallo Marie, hast du am Samstag Zeit? Wir könnten zusammen italienisch essen gehen. Sag mir bitte kurz Bescheid." },
  },
  {
    slug: "likes-dislikes", level: "A1", title: "Likes & Dislikes", de: "Vorlieben & Abneigungen", theme: "opinions",
    summary: "Use mögen, gefallen and schmecken to express taste.",
    dlg: { title: "Schmeckt es dir?", lines: [
      ["Gastgeber", "Schmeckt dir die Suppe?", "Do you like the soup?"],
      ["Gast", "Ja, sie schmeckt sehr gut!", "Yes, it tastes very good!"],
      ["Gastgeber", "Und der Salat?", "And the salad?"],
      ["Gast", "Den mag ich leider nicht so gern.", "That one I unfortunately do not like so much."]],
      q: "What does the guest like?", opts: ["The soup", "The salad", "Neither"], a: 0,
      note: "schmecken takes a dative person: Schmeckt dir …?" },
    read: { title: "Geschmackssache", de: "Mir gefällt die neue Wohnung sehr. Die Farben mag ich nicht so gern, aber das ist Geschmackssache. Am besten gefällt mir der Balkon.",
      en: "I like the new flat a lot. I do not like the colours much, but that is a matter of taste. I like the balcony best.",
      q: "What does the writer like best?", opts: ["The colours", "The balcony", "The kitchen"], a: 1,
      note: "gefallen also takes a dative person: mir gefällt …" },
    pron: { de: "Das gefällt mir sehr gut.", en: "I like that very much.", stress: "das ge-FÄLLT mir sehr GUT", tip: "gefällt stresses the second syllable; ä is open." },
    blanks: [
      { s: "___ gefällt das Bild.", en: "I like the picture.", opts: ["Mir", "Ich", "Mich"], a: 0, note: "gefallen requires the dative mir." },
      { s: "Ich ___ keinen Fisch.", en: "I do not like fish.", opts: ["mag", "magst", "mögen"], a: 0, note: "ich mag is the first person of mögen." }],
    order: { answer: ["Der", "Kuchen", "schmeckt", "mir", "sehr", "gut"], en: "I like the cake very much.", note: "Dative person after the verb." },
    vocab: [["mögen", "to like"], ["gefallen", "to please"], ["lieblings-", "favourite"], ["furchtbar", "terrible"]],
    prag: { scenario: "You are served a dish you dislike at someone's home.", q: "What is polite?", opts: ["Das schmeckt schrecklich.", "Danke, das ist nicht ganz mein Geschmack, aber sehr nett von dir.", "Ich esse das nicht."], a: 1, note: "Soften the refusal and thank the host." },
    write: { prompt: "Was mögen Sie und was nicht? Drei Sätze.", hint: "Use: Ich mag …, … gefällt mir …, … schmeckt mir nicht.", sample: "Ich mag deutsches Brot sehr. Klassische Musik gefällt mir gut. Kaffee ohne Zucker schmeckt mir leider nicht." },
  },
  {
    slug: "animals-nature", level: "A1", title: "Animals & Nature", de: "Tiere & Natur", theme: "nature",
    summary: "Talk about pets, animals and being outdoors.",
    dlg: { title: "Hast du ein Haustier?", lines: [
      ["Ida", "Hast du ein Haustier?", "Do you have a pet?"],
      ["Nico", "Ja, einen Hund. Er heißt Bruno.", "Yes, a dog. His name is Bruno."],
      ["Ida", "Wie alt ist er?", "How old is he?"],
      ["Nico", "Drei Jahre. Er läuft gern im Wald.", "Three years. He likes running in the forest."]],
      q: "What pet does Nico have?", opts: ["A cat", "A dog", "A bird"], a: 1,
      note: "ein Haustier haben takes the accusative: einen Hund." },
    read: { title: "Im Wald", de: "Am Wochenende gehen wir gern im Wald spazieren. Dort sieht man manchmal Rehe und viele Vögel. Die Luft ist frisch und es ist sehr ruhig.",
      en: "At the weekend we like walking in the forest. There you sometimes see deer and many birds. The air is fresh and it is very quiet.",
      q: "What can you see there?", opts: ["Deer and birds", "Fish", "Horses"], a: 0,
      note: "man sieht is the impersonal you see." },
    pron: { de: "Mein Hund läuft gern im Wald.", en: "My dog likes running in the forest.", stress: "mein HUND läuft gern im VALD", tip: "The German w in Wald is a v; the final d sounds like t." },
    blanks: [
      { s: "Ich habe ___ Katze.", en: "I have a cat.", opts: ["eine", "einen", "ein"], a: 0, note: "die Katze stays eine in the accusative." },
      { s: "Die Vögel ___ im Garten.", en: "The birds sing in the garden.", opts: ["singen", "singt", "gesungen"], a: 0, note: "Plural subject takes the -en ending." }],
    order: { answer: ["Wir", "gehen", "im", "Park", "spazieren"], en: "We go for a walk in the park.", note: "spazieren gehen keeps both verbs at the end." },
    vocab: [["der Hund", "the dog"], ["die Katze", "the cat"], ["der Baum", "the tree"], ["der See", "the lake"]],
    prag: { scenario: "A dog runs towards you and the owner is nearby.", q: "What can you ask?", opts: ["Nehmen Sie den Hund weg!", "Ist er freundlich? Darf ich ihn streicheln?", "Hunde sind verboten."], a: 1, note: "Ask before touching someone's dog." },
    write: { prompt: "Beschreiben Sie ein Tier, das Sie mögen. Drei Sätze.", hint: "Use: Ich mag …, Es ist …, Am liebsten …", sample: "Ich mag Katzen sehr. Sie sind ruhig und sehr selbstständig. Am liebsten sitze ich abends mit einer Katze auf dem Sofa." },
  },
  {
    slug: "city-country", level: "A1", title: "City & Countryside", de: "Stadt & Land", theme: "places",
    summary: "Compare living in a city and in a village in simple terms.",
    dlg: { title: "Stadt oder Dorf?", lines: [
      ["Ravi", "Wohnst du gern in der Stadt?", "Do you like living in the city?"],
      ["Hanna", "Ja, alles ist nah. Aber es ist laut.", "Yes, everything is close. But it is loud."],
      ["Ravi", "Ich wohne auf dem Land. Dort ist es ruhig.", "I live in the countryside. It is quiet there."]],
      q: "Where does Ravi live?", opts: ["In the city", "In the countryside", "By the sea"], a: 1,
      note: "auf dem Land is the fixed phrase for the countryside." },
    read: { title: "Mein Ort", de: "Ich wohne in einer Kleinstadt mit zwanzigtausend Einwohnern. Es gibt einen Marktplatz, zwei Schulen und ein Schwimmbad. Zum Einkaufen fahre ich in die große Stadt.",
      en: "I live in a small town with twenty thousand inhabitants. There is a market square, two schools and a swimming pool. For shopping I drive to the big city.",
      q: "How many inhabitants?", opts: ["2,000", "20,000", "200,000"], a: 1,
      note: "Es gibt + accusative lists what exists in a place." },
    pron: { de: "Ich wohne auf dem Land.", en: "I live in the countryside.", stress: "ich WOH-ne auf dem LAND", tip: "The final d in Land sounds like t." },
    blanks: [
      { s: "Ich wohne ___ der Stadt.", en: "I live in the city.", opts: ["in", "auf", "an"], a: 0, note: "in der Stadt versus auf dem Land." },
      { s: "___ gibt hier einen Park.", en: "There is a park here.", opts: ["Es", "Das", "Da"], a: 0, note: "Es gibt is the fixed existential phrase." }],
    order: { answer: ["In", "meiner", "Stadt", "gibt", "es", "viele", "Cafés"], en: "In my city there are many cafés.", note: "Place first, then gibt es." },
    vocab: [["das Dorf", "the village"], ["die Einwohner", "the inhabitants"], ["laut", "loud"], ["ruhig", "quiet"]],
    prag: { scenario: "Someone criticises the town you live in.", q: "How do you answer politely but honestly?", opts: ["Du hast keine Ahnung.", "Stimmt, es ist klein, aber mir gefällt die Ruhe.", "Egal."], a: 1, note: "Agree partly, then add your own view." },
    write: { prompt: "Wo wohnen Sie und wie ist es dort? Drei Sätze.", hint: "Use: Ich wohne in …, Es gibt …, Mir gefällt …", sample: "Ich wohne in einer mittelgroßen Stadt im Süden. Es gibt viele Cafés und einen großen Park. Mir gefällt besonders, dass alles zu Fuß erreichbar ist." },
  },
  {
    slug: "a1-recap", level: "A1", title: "A1 Recap & Everyday Survival", de: "A1 Wiederholung", theme: "review",
    summary: "Combine greetings, shopping, time and directions in real situations.",
    dlg: { title: "Ein normaler Tag", lines: [
      ["Nachbarin", "Guten Morgen! Wohin gehen Sie so früh?", "Good morning! Where are you going so early?"],
      ["Sie", "Guten Morgen! Ich gehe einkaufen und dann zum Arzt.", "Good morning! I am going shopping and then to the doctor."],
      ["Nachbarin", "Dann einen schönen Tag!", "Have a nice day then!"],
      ["Sie", "Danke, Ihnen auch.", "Thanks, you too."]],
      q: "Where is the speaker going after shopping?", opts: ["Home", "To the doctor", "To work"], a: 1,
      note: "zum Arzt uses zu + dem for people and institutions." },
    read: { title: "Mein Tag", de: "Ich stehe um halb sieben auf und trinke Kaffee. Um acht fahre ich mit dem Bus zur Arbeit. Am Abend koche ich und sehe ein bisschen fern.",
      en: "I get up at half past six and drink coffee. At eight I take the bus to work. In the evening I cook and watch a bit of television.",
      q: "When does the writer get up?", opts: ["06:30", "07:30", "08:00"], a: 0,
      note: "halb sieben means half an hour before seven." },
    pron: { de: "Entschuldigung, wie komme ich zum Bahnhof?", en: "Excuse me, how do I get to the station?", stress: "ent-SCHUL-di-gung wie KO-mme ich tsum BAHN-hof", tip: "Keep Entschuldigung fluent; the stress sits on -schul-." },
    blanks: [
      { s: "Ich stehe um sieben Uhr ___.", en: "I get up at seven.", opts: ["auf", "an", "aus"], a: 0, note: "aufstehen is separable." },
      { s: "Wie komme ich ___ Bahnhof?", en: "How do I get to the station?", opts: ["zum", "zur", "nach"], a: 0, note: "der Bahnhof takes zum." }],
    order: { answer: ["Am", "Abend", "koche", "ich", "gern", "zu", "Hause"], en: "In the evening I like cooking at home.", note: "Time first, verb second, place at the end." },
    vocab: [["der Alltag", "everyday life"], ["früh", "early"], ["spät", "late"], ["zu Fuß", "on foot"]],
    prag: { scenario: "You meet your neighbour in the stairwell in the morning.", q: "What do you say?", opts: ["Nichts.", "Guten Morgen! Schönen Tag noch.", "Was wollen Sie?"], a: 1, note: "A short greeting is expected in German buildings." },
    write: { prompt: "Beschreiben Sie Ihren normalen Tag in vier Sätzen.", hint: "Use: Ich stehe … auf, Dann …, Am Nachmittag …, Am Abend …", sample: "Ich stehe um sechs Uhr auf und frühstücke. Dann fahre ich mit der Bahn zur Arbeit. Am Nachmittag kaufe ich schnell ein. Am Abend koche ich und lese ein Buch." },
  },
];
