import type { LessonSeed } from "./types";

export const A2: LessonSeed[] = [
  {
    slug: "perfekt-sein", level: "A2", title: "Perfekt with sein", de: "Perfekt mit sein", theme: "grammar",
    summary: "Form the Perfekt tense with sein for verbs of motion and change of state.",
    dlg: { title: "Wochenende in Hamburg", lines: [
      ["Petra", "Was hast du am Wochenende gemacht?", "What did you do on the weekend?"],
      ["Jonas", "Ich bin nach Hamburg gefahren.", "I went to Hamburg."],
      ["Petra", "Wie bist du dorthin gekommen?", "How did you get there?"],
      ["Jonas", "Ich bin mit dem Zug gefahren und dann viel gelaufen.", "I went by train and then walked a lot."]],
      q: "How did Jonas travel to Hamburg?", opts: ["By train", "By car", "By plane"], a: 0,
      note: "Verbs of motion like fahren, gehen and kommen use sein as the auxiliary in the Perfekt." },
    read: { title: "Ein Ausflug", de: "Am Samstag ist Lena früh aufgestanden. Sie ist mit dem Fahrrad zum See gefahren und dort geschwommen. Am Abend ist sie müde nach Hause gekommen.",
      en: "On Saturday Lena got up early. She cycled to the lake and swam there. In the evening she came home tired.",
      q: "How did Lena get to the lake?", opts: ["By bike", "By bus", "On foot"], a: 0,
      note: "aufstehen, fahren and kommen all take sein because they describe motion or a change of state." },
    pron: { de: "Ich bin gestern spät aufgestanden.", en: "I got up late yesterday.", stress: "ich bin GES-tern SPÄT AUF-ge-schtan-den", tip: "Stress falls on the separable prefix auf- in aufgestanden." },
    blanks: [
      { s: "Sie ___ gestern nach Berlin gefahren.", en: "She traveled to Berlin yesterday.", opts: ["hat", "ist", "war"], a: 1, note: "fahren takes sein as the Perfekt auxiliary." },
      { s: "Wir ___ um sechs Uhr aufgewacht.", en: "We woke up at six o'clock.", opts: ["haben", "sind", "war"], a: 1, note: "aufwachen describes a change of state, so it takes sein." }],
    order: { answer: ["Er", "ist", "spät", "nach", "Hause", "gekommen"], en: "He came home late.", note: "sein + past participle: ist gekommen." },
    vocab: [["fahren", "to travel/drive"], ["kommen", "to come"], ["aufstehen", "to get up"], ["laufen", "to run/walk"]],
    prag: { scenario: "A friend asks how your trip went and you want to describe your journey.", q: "What is the natural way to start?", opts: ["Ich bin mit dem Zug gefahren.", "Ich habe mit dem Zug gefahren.", "Ich fahre mit dem Zug."], a: 0, note: "Motion verbs need sein in the Perfekt, not haben." },
    write: { prompt: "Was haben Sie letztes Wochenende gemacht? Schreiben Sie drei Sätze mit sein-Verben.", hint: "Use: Ich bin …, Dann bin ich …, Am Abend bin ich …", sample: "Ich bin am Samstag ins Kino gegangen. Dann bin ich mit Freunden spazieren gegangen. Am Abend bin ich früh eingeschlafen." },
  },
  {
    slug: "praeteritum", level: "A2", title: "Präteritum of common verbs", de: "Präteritum wichtiger Verben", theme: "grammar",
    summary: "Use the simple past of haben, sein and modal verbs in written and spoken German.",
    dlg: { title: "Als ich klein war", lines: [
      ["Oma", "Als ich klein war, hatten wir kein Fernsehen.", "When I was young, we had no television."],
      ["Tim", "Was habt ihr dann gemacht?", "What did you do then?"],
      ["Oma", "Wir spielten draußen und lasen viel.", "We played outside and read a lot."]],
      q: "What did grandma's family not have?", opts: ["A television", "A car", "A garden"], a: 0,
      note: "war and hatten are the Präteritum forms of sein and haben, common even in speech." },
    read: { title: "Meine Kindheit", de: "Ich wuchs in einem kleinen Dorf auf. Meine Eltern hatten einen Bauernhof. Ich musste morgens früh aufstehen und half meinem Vater bei der Arbeit.",
      en: "I grew up in a small village. My parents had a farm. I had to get up early in the morning and helped my father with the work.",
      q: "Where did the writer grow up?", opts: ["In a village", "In a city", "Abroad"], a: 0,
      note: "The Präteritum is common in narrative and written texts about the past." },
    pron: { de: "Ich hatte keine Zeit.", en: "I had no time.", stress: "ich HAT-te KEI-ne TSEIT", tip: "Double t in hatte is pronounced as one sharp t sound." },
    blanks: [
      { s: "Früher ___ wir keinen Computer.", en: "In the past we had no computer.", opts: ["hatten", "hatte", "haben"], a: 0, note: "wir hatten is the plural Präteritum of haben." },
      { s: "Er ___ als Kind sehr schüchtern.", en: "He was very shy as a child.", opts: ["war", "ist", "wart"], a: 0, note: "war is the Präteritum of sein for er/sie/es." }],
    order: { answer: ["Sie", "konnte", "sehr", "gut", "singen"], en: "She could sing very well.", note: "Modal verbs commonly appear in the Präteritum: konnte." },
    vocab: [["aufwachsen", "to grow up"], ["früher", "earlier/in the past"], ["das Dorf", "the village"], ["schüchtern", "shy"]],
    prag: { scenario: "You are writing a short story about your childhood for a language class.", q: "Which tense fits best?", opts: ["Präteritum", "Perfekt", "Präsens"], a: 0, note: "Written narratives about the past typically use the Präteritum." },
    write: { prompt: "Beschreiben Sie Ihre Kindheit. Nutzen Sie das Präteritum.", hint: "Use: Ich war …, Wir hatten …, Ich musste …", sample: "Ich war als Kind sehr neugierig. Wir hatten einen Hund und einen großen Garten. Ich musste jeden Tag mein Zimmer aufräumen." },
  },
  {
    slug: "dative", level: "A2", title: "Dative case", de: "Der Dativ", theme: "grammar",
    summary: "Use the dative case with verbs like helfen, danken and geben.",
    dlg: { title: "Kannst du mir helfen?", lines: [
      ["Nina", "Kannst du mir helfen?", "Can you help me?"],
      ["Paul", "Klar, was brauchst du?", "Sure, what do you need?"],
      ["Nina", "Ich möchte meiner Schwester ein Geschenk kaufen.", "I want to buy my sister a gift."],
      ["Paul", "Gib ihr doch ein Buch.", "Give her a book."]],
      q: "Who does Nina want to buy a gift for?", opts: ["Her sister", "Her mother", "Her friend"], a: 0,
      note: "helfen and geben both require the dative case for the person involved." },
    read: { title: "Ein Geschenk für den Vater", de: "Zum Geburtstag schenke ich meinem Vater ein neues Buch. Er dankt mir immer sehr herzlich. Ich helfe ihm auch gern im Garten.",
      en: "For his birthday I give my father a new book. He always thanks me very warmly. I also like to help him in the garden.",
      q: "What does the writer give the father?", opts: ["A book", "A watch", "A plant"], a: 0,
      note: "meinem Vater and mir are dative forms after schenken and danken." },
    pron: { de: "Ich helfe meiner Mutter.", en: "I am helping my mother.", stress: "ich HEL-fe MEI-ner MUT-ter", tip: "meiner takes the feminine dative ending -er." },
    blanks: [
      { s: "Ich gebe ___ Freund ein Buch.", en: "I am giving my friend a book.", opts: ["mein", "meinem", "meinen"], a: 1, note: "der Freund is masculine, dative meinem Freund." },
      { s: "Wir danken ___ Lehrerin.", en: "We thank the teacher.", opts: ["die", "der", "den"], a: 1, note: "danken always takes the dative: der Lehrerin." }],
    order: { answer: ["Er", "schenkt", "seiner", "Freundin", "Blumen"], en: "He gives his girlfriend flowers.", note: "seiner Freundin is the feminine dative form." },
    vocab: [["helfen", "to help"], ["danken", "to thank"], ["schenken", "to give as a gift"], ["gehören", "to belong to"]],
    prag: { scenario: "A colleague is struggling to carry heavy boxes.", q: "What do you offer?", opts: ["Ich helfe dir.", "Ich helfe du.", "Ich helfe dich."], a: 0, note: "helfen requires the dative pronoun dir, not the accusative dich." },
    write: { prompt: "Wem helfen Sie oft? Schreiben Sie drei Sätze mit Dativ-Verben.", hint: "Use: Ich helfe …, Ich danke …, Ich schenke …", sample: "Ich helfe meinem Nachbarn oft im Garten. Ich danke meinen Eltern für ihre Unterstützung. Zu Weihnachten schenke ich meiner Schwester ein Buch." },
  },
  {
    slug: "two-way-prepositions", level: "A2", title: "Two-way prepositions", de: "Wechselpräpositionen", theme: "grammar",
    summary: "Choose between dative and accusative with prepositions like in, auf and an.",
    dlg: { title: "Wo stellst du die Vase hin?", lines: [
      ["Marie", "Wo stellst du die Vase hin?", "Where are you putting the vase?"],
      ["Kevin", "Ich stelle sie auf den Tisch.", "I am putting it on the table."],
      ["Marie", "Und jetzt steht sie auf dem Tisch, schön!", "And now it's standing on the table, nice!"]],
      q: "Where does the vase end up?", opts: ["On the table", "Under the table", "Next to the table"], a: 0,
      note: "stellen (movement) takes accusative; stehen (position) takes dative." },
    read: { title: "Im Klassenzimmer", de: "Die Lehrerin hängt das Bild an die Wand. Jetzt hängt das Bild an der Wand. Die Schüler legen ihre Hefte auf den Tisch.",
      en: "The teacher hangs the picture on the wall. Now the picture hangs on the wall. The students put their notebooks on the table.",
      q: "Where does the teacher hang the picture?", opts: ["On the wall", "On the door", "On the shelf"], a: 0,
      note: "hängen as movement (accusative) vs. hängen as position (dative)." },
    pron: { de: "Das Bild hängt an der Wand.", en: "The picture hangs on the wall.", stress: "das BILD hängt an der WAND", tip: "The a in Wand is long and open." },
    blanks: [
      { s: "Ich lege das Buch auf ___ Tisch.", en: "I am putting the book on the table (movement).", opts: ["den", "dem", "der"], a: 0, note: "Movement/direction: auf + accusative den Tisch." },
      { s: "Das Buch liegt auf ___ Tisch.", en: "The book is lying on the table (position).", opts: ["den", "dem", "der"], a: 1, note: "Position/location: auf + dative dem Tisch." }],
    order: { answer: ["Sie", "geht", "in", "die", "Küche"], en: "She is going into the kitchen.", note: "Direction with in takes the accusative: in die Küche." },
    vocab: [["stellen", "to put/place upright"], ["legen", "to put/lay down"], ["hängen", "to hang"], ["die Wand", "the wall"]],
    prag: { scenario: "You want to tell someone where you just put their keys.", q: "Which is correct if you placed them on the shelf?", opts: ["Ich habe die Schlüssel auf das Regal gelegt.", "Ich habe die Schlüssel auf dem Regal gelegt.", "Ich habe die Schlüssel auf des Regal gelegt."], a: 0, note: "The action of putting something down (legen) takes the accusative." },
    write: { prompt: "Beschreiben Sie Ihr Zimmer mit Wechselpräpositionen.", hint: "Use: … steht in …, … liegt auf …, … hängt an …", sample: "Mein Schreibtisch steht am Fenster. Meine Bücher liegen auf dem Regal. Ein Poster hängt an der Wand." },
  },
  {
    slug: "comparatives", level: "A2", title: "Comparatives and superlatives", de: "Komparativ und Superlativ", theme: "grammar",
    summary: "Compare people and things using -er and am -sten forms.",
    dlg: { title: "Welche Stadt ist schöner?", lines: [
      ["Leon", "Ist Berlin größer als München?", "Is Berlin bigger than Munich?"],
      ["Sofia", "Ja, aber München finde ich schöner.", "Yes, but I find Munich more beautiful."],
      ["Leon", "Für mich ist Hamburg am schönsten.", "For me, Hamburg is the most beautiful."]],
      q: "Which city does Leon like best?", opts: ["Hamburg", "Berlin", "München"], a: 0,
      note: "am schönsten is the superlative form used with sein." },
    read: { title: "Vergleiche im Alltag", de: "Der Zug ist schneller als das Auto, aber das Fahrrad ist billiger. Am gesündesten ist es natürlich, zu Fuß zu gehen.",
      en: "The train is faster than the car, but the bike is cheaper. Of course, walking is the healthiest.",
      q: "What is described as the healthiest option?", opts: ["Walking", "Cycling", "The train"], a: 0,
      note: "gesund becomes am gesündesten in the superlative, with an umlaut." },
    pron: { de: "Das ist viel besser.", en: "That is much better.", stress: "das ist FIEL BES-ser", tip: "besser is the irregular comparative of gut." },
    blanks: [
      { s: "Mein Bruder ist ___ als ich.", en: "My brother is taller than me.", opts: ["groß", "größer", "am größten"], a: 1, note: "Comparative with als: größer als." },
      { s: "Das ist das ___ Restaurant der Stadt.", en: "That is the best restaurant in town.", opts: ["gute", "bessere", "beste"], a: 2, note: "beste is the superlative adjective form of gut." }],
    order: { answer: ["Dieser", "Film", "ist", "interessanter", "als", "der", "andere"], en: "This film is more interesting than the other one.", note: "Comparative + als introduces the comparison." },
    vocab: [["schnell", "fast"], ["billig", "cheap"], ["gesund", "healthy"], ["am liebsten", "most preferably"]],
    prag: { scenario: "A friend asks which of two cafés you prefer.", q: "How do you express a clear preference?", opts: ["Dieses Café ist besser.", "Dieses Café ist gut.", "Dieses Café ist mehr gut."], a: 0, note: "besser is the comparative form used to express preference." },
    write: { prompt: "Vergleichen Sie zwei Städte oder Orte, die Sie kennen.", hint: "Use: … ist größer als …, … ist billiger, am schönsten ist …", sample: "München ist kleiner als Berlin, aber teurer. Berlin hat mehr Museen. Am schönsten finde ich aber Hamburg wegen des Hafens." },
  },
  {
    slug: "subordinate-clauses", level: "A2", title: "Subordinate clauses with weil/dass", de: "Nebensätze mit weil und dass", theme: "grammar",
    summary: "Give reasons and report statements with weil and dass, sending the verb to the end.",
    dlg: { title: "Warum lernst du Deutsch?", lines: [
      ["Interviewer", "Warum lernst du Deutsch?", "Why are you learning German?"],
      ["Amir", "Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte.", "I am learning German because I want to work in Germany."],
      ["Interviewer", "Denkst du, dass es schwer ist?", "Do you think it is difficult?"],
      ["Amir", "Ich glaube, dass die Grammatik am schwersten ist.", "I believe the grammar is the hardest."]],
      q: "Why does Amir learn German?", opts: ["To work in Germany", "For a holiday", "For fun"], a: 0,
      note: "weil sends the conjugated verb to the end of the clause." },
    read: { title: "Warum ich umziehe", de: "Ich ziehe um, weil meine Wohnung zu klein geworden ist. Meine Familie meint, dass ein Umzug eine gute Idee ist. Ich hoffe, dass ich bald eine neue Wohnung finde.",
      en: "I am moving because my flat has become too small. My family thinks that moving is a good idea. I hope that I find a new flat soon.",
      q: "Why is the writer moving?", opts: ["The flat is too small", "The rent is too high", "New job"], a: 0,
      note: "dass also pushes the verb to the end: dass ein Umzug eine gute Idee ist." },
    pron: { de: "Ich denke, dass es klappt.", en: "I think it will work out.", stress: "ich DEN-ke, dass es KLAPPT", tip: "The verb klappt moves to the very end after dass." },
    blanks: [
      { s: "Ich bin müde, weil ich zu wenig ___.", en: "I am tired because I sleep too little.", opts: ["schlafe", "schlafen", "schläft"], a: 0, note: "After weil the verb goes to the end: ich schlafe." },
      { s: "Sie sagt, ___ sie morgen kommt.", en: "She says that she is coming tomorrow.", opts: ["weil", "dass", "wenn"], a: 1, note: "dass introduces reported statements." }],
    order: { answer: ["Ich", "bleibe", "zu", "Hause", "weil", "es", "regnet"], en: "I am staying home because it is raining.", note: "The verb regnet goes to the very end of the weil-clause." },
    vocab: [["weil", "because"], ["dass", "that"], ["glauben", "to believe"], ["hoffen", "to hope"]],
    prag: { scenario: "A friend asks why you cancelled your plans.", q: "Which explanation is grammatically correct?", opts: ["Ich kann nicht kommen, weil ich bin krank.", "Ich kann nicht kommen, weil ich krank bin.", "Ich kann nicht kommen, weil krank ich bin."], a: 1, note: "In a weil-clause, the conjugated verb (bin) moves to the end." },
    write: { prompt: "Warum lernen Sie Deutsch? Erklären Sie mit weil und dass.", hint: "Use: Ich lerne Deutsch, weil …, Ich denke, dass …", sample: "Ich lerne Deutsch, weil ich hier lebe und arbeite. Ich denke, dass Deutsch eine wichtige Sprache in Europa ist. Ich hoffe, dass ich bald besser sprechen kann." },
  },
  {
    slug: "time-clauses", level: "A2", title: "Time clauses with wenn/als", de: "Nebensätze mit wenn und als", theme: "grammar",
    summary: "Distinguish wenn for repeated or future events and als for single past events.",
    dlg: { title: "Als ich in Berlin ankam", lines: [
      ["Julia", "Als ich in Berlin ankam, hat es geregnet.", "When I arrived in Berlin, it was raining."],
      ["Ben", "Und wenn du wieder hinfährst?", "And when you go there again?"],
      ["Julia", "Wenn ich Zeit habe, besuche ich das Museum.", "If/when I have time, I will visit the museum."]],
      q: "What happened when Julia first arrived in Berlin?", opts: ["It was raining", "It was sunny", "It was snowing"], a: 0,
      note: "als refers to one single event in the past; wenn refers to repeated or future events." },
    read: { title: "Kindheitserinnerungen", de: "Als ich klein war, wohnten wir am Meer. Wenn es warm war, sind wir immer schwimmen gegangen. Wenn ich heute ans Meer fahre, denke ich an meine Kindheit.",
      en: "When I was little, we lived by the sea. When it was warm, we always went swimming. When I go to the sea today, I think of my childhood.",
      q: "Where did the family live in the writer's childhood?", opts: ["By the sea", "In the mountains", "In a city"], a: 0,
      note: "als klein war = a single ongoing past situation; wenn es warm war = repeated occasions." },
    pron: { de: "Als ich ankam, war niemand da.", en: "When I arrived, nobody was there.", stress: "als ich AN-kam, war NIE-mand da", tip: "The separable verb ankommen splits: ich kam an." },
    blanks: [
      { s: "___ ich letztes Jahr nach Spanien fuhr, war es sehr heiß.", en: "When I went to Spain last year, it was very hot.", opts: ["Wenn", "Als", "Dass"], a: 1, note: "A single past event uses als, not wenn." },
      { s: "___ ich Zeit habe, rufe ich dich an.", en: "When(ever) I have time, I'll call you.", opts: ["Als", "Wenn", "Weil"], a: 1, note: "wenn is used for future or repeated situations." }],
    order: { answer: ["Wenn", "es", "regnet", "bleibe", "ich", "zu", "Hause"], en: "When it rains, I stay home.", note: "wenn-clause first, then verb-subject order in the main clause." },
    vocab: [["ankommen", "to arrive"], ["als", "when (single past event)"], ["wenn", "when/if (repeated/future)"], ["die Erinnerung", "the memory"]],
    prag: { scenario: "You are telling a friend about the one time you met a famous singer.", q: "Which word introduces this single past event?", opts: ["wenn", "als", "dass"], a: 1, note: "A unique, one-time past event always uses als." },
    write: { prompt: "Erzählen Sie von einer Erinnerung mit als und einer Gewohnheit mit wenn.", hint: "Use: Als ich …, war/hatte …, Wenn ich heute …, dann …", sample: "Als ich zehn Jahre alt war, zogen wir nach Köln um. Wenn ich heute meine alte Straße besuche, erinnere ich mich an meine Kindheit." },
  },
  {
    slug: "future-werden", level: "A2", title: "Future with werden", de: "Futur mit werden", theme: "grammar",
    summary: "Talk about future plans using the werden + infinitive construction.",
    dlg: { title: "Pläne für nächstes Jahr", lines: [
      ["Sven", "Was wirst du nächstes Jahr machen?", "What will you do next year?"],
      ["Amina", "Ich werde nach Australien reisen.", "I will travel to Australia."],
      ["Sven", "Wow, wirst du dort auch arbeiten?", "Wow, will you also work there?"],
      ["Amina", "Ja, ich werde in einem Café arbeiten.", "Yes, I will work in a café."]],
      q: "What will Amina do next year?", opts: ["Travel to Australia", "Study in Germany", "Move to France"], a: 0,
      note: "werden + infinitive expresses future plans, often with certainty or intention." },
    read: { title: "Zukunftspläne", de: "Nächstes Jahr werde ich meine Ausbildung beenden. Danach werde ich eine Wohnung suchen. Ich hoffe, dass ich einen guten Job finden werde.",
      en: "Next year I will finish my training. After that I will look for a flat. I hope that I will find a good job.",
      q: "What will the writer finish next year?", opts: ["Training/apprenticeship", "University", "A course"], a: 0,
      note: "The infinitive (beenden, suchen) goes to the end of the sentence with werden." },
    pron: { de: "Ich werde morgen anrufen.", en: "I will call tomorrow.", stress: "ich WER-de MOR-gen AN-ru-fen", tip: "werde is unstressed compared to the infinitive at the end." },
    blanks: [
      { s: "Wir ___ nächstes Jahr heiraten.", en: "We will get married next year.", opts: ["werden", "wird", "werde"], a: 0, note: "wir werden is the plural form of werden." },
      { s: "Es ___ morgen regnen.", en: "It will rain tomorrow.", opts: ["wird", "werden", "werdet"], a: 0, note: "es wird is the third person singular." }],
    order: { answer: ["Ich", "werde", "bald", "ein", "Auto", "kaufen"], en: "I will buy a car soon.", note: "werden in position two, infinitive kaufen at the end." },
    vocab: [["die Zukunft", "the future"], ["die Ausbildung", "the training/apprenticeship"], ["heiraten", "to get married"], ["planen", "to plan"]],
    prag: { scenario: "A friend asks about your career plans for the future.", q: "Which sentence expresses a clear future plan?", opts: ["Ich werde eine neue Stelle suchen.", "Ich suche eine neue Stelle gestern.", "Ich habe eine neue Stelle gesucht."], a: 0, note: "werden + infinitive is the clearest way to express future intentions." },
    write: { prompt: "Was werden Sie in den nächsten Jahren machen? Drei Sätze mit werden.", hint: "Use: Ich werde …, Danach werde ich …, Ich hoffe, dass ich … werde.", sample: "Ich werde nächstes Jahr meinen Deutschkurs beenden. Danach werde ich eine neue Arbeit suchen. Ich hoffe, dass ich in Deutschland bleiben werde." },
  },
  {
    slug: "reflexive-verbs", level: "A2", title: "Reflexive verbs", de: "Reflexive Verben", theme: "grammar",
    summary: "Use reflexive pronouns with everyday verbs like sich freuen and sich erinnern.",
    dlg: { title: "Ich freue mich schon", lines: [
      ["Tanja", "Ich freue mich schon auf die Ferien.", "I am already looking forward to the holidays."],
      ["David", "Ich auch! Ich muss mich aber noch erholen.", "Me too! But I still need to recover."],
      ["Tanja", "Erinnerst du dich an unseren letzten Urlaub?", "Do you remember our last holiday?"]],
      q: "What is Tanja looking forward to?", opts: ["The holidays", "Work", "The weekend"], a: 0,
      note: "sich freuen auf takes a reflexive pronoun matching the subject." },
    read: { title: "Mein Morgen", de: "Ich stehe auf und dusche mich. Dann ziehe ich mich schnell an. Ich beeile mich, weil der Bus um acht Uhr fährt.",
      en: "I get up and shower. Then I get dressed quickly. I hurry because the bus leaves at eight.",
      q: "Why does the writer hurry?", opts: ["The bus leaves at eight", "School starts early", "It is raining"], a: 0,
      note: "sich duschen, sich anziehen and sich beeilen are common reflexive verbs." },
    pron: { de: "Ich freue mich auf dich.", en: "I am looking forward to seeing you.", stress: "ich FREU-e mich auf DICH", tip: "mich is short and unstressed, the emphasis is on freue and dich." },
    blanks: [
      { s: "Ich muss ___ beeilen.", en: "I have to hurry.", opts: ["mich", "mir", "mein"], a: 0, note: "sich beeilen takes the accusative reflexive pronoun mich." },
      { s: "Erinnerst du ___ an mich?", en: "Do you remember me?", opts: ["dich", "dir", "dein"], a: 0, note: "sich erinnern an + accusative pronoun dich." }],
    order: { answer: ["Wir", "freuen", "uns", "auf", "das", "Fest"], en: "We are looking forward to the party.", note: "The reflexive pronoun uns follows the verb directly." },
    vocab: [["sich freuen", "to be happy/look forward"], ["sich erinnern", "to remember"], ["sich beeilen", "to hurry"], ["sich erholen", "to recover/relax"]],
    prag: { scenario: "You want to tell a friend you are excited about an upcoming trip.", q: "Which sentence is correct?", opts: ["Ich freue mich auf die Reise.", "Ich freue auf die Reise.", "Ich freue mir auf die Reise."], a: 0, note: "sich freuen requires the accusative reflexive pronoun mich." },
    write: { prompt: "Beschreiben Sie Ihren Morgen mit reflexiven Verben.", hint: "Use: Ich stehe auf, ich dusche mich, ich ziehe mich an, ich beeile mich.", sample: "Ich stehe um sieben Uhr auf und dusche mich sofort. Danach ziehe ich mich an und trinke einen Kaffee. Ich beeile mich, weil die Arbeit um acht beginnt." },
  },
  {
    slug: "konjunktiv-politeness", level: "A2", title: "Konjunktiv II politeness", de: "Höflichkeit mit Konjunktiv II", theme: "grammar",
    summary: "Make polite requests and wishes using hätte, wäre and würde.",
    dlg: { title: "Im Restaurant", lines: [
      ["Kellner", "Was hätten Sie gern?", "What would you like?"],
      ["Gast", "Ich würde gern die Suppe probieren.", "I would like to try the soup."],
      ["Kellner", "Möchten Sie sonst noch etwas?", "Would you like anything else?"],
      ["Gast", "Könnten Sie mir bitte auch Wasser bringen?", "Could you also bring me some water, please?"]],
      q: "What does the guest want to try?", opts: ["The soup", "The salad", "The cake"], a: 0,
      note: "würde + infinitive and könnten express polite requests." },
    read: { title: "Ein höflicher Brief", de: "Ich hätte gern einen Termin nächste Woche. Wäre Dienstag möglich? Ich würde mich über eine schnelle Antwort freuen.",
      en: "I would like an appointment next week. Would Tuesday be possible? I would be happy about a quick reply.",
      q: "What is the writer requesting?", opts: ["An appointment", "A refund", "A job"], a: 0,
      note: "hätte gern and wäre möglich are polite Konjunktiv II forms." },
    pron: { de: "Könnten Sie mir helfen?", en: "Could you help me?", stress: "KÖNN-ten Sie mir HEL-fen", tip: "könnten has a soft ö and stresses the first syllable." },
    blanks: [
      { s: "___ Sie mir bitte das Salz geben?", en: "Could you pass me the salt, please?", opts: ["Können", "Könnten", "Konnten"], a: 1, note: "Könnten is the polite Konjunktiv II form of können." },
      { s: "Ich ___ gern einen Kaffee.", en: "I would like a coffee.", opts: ["hätte", "habe", "hatte"], a: 0, note: "Ich hätte gern is the standard polite ordering phrase." }],
    order: { answer: ["Ich", "würde", "gern", "einen", "Tisch", "reservieren"], en: "I would like to reserve a table.", note: "würde + infinitive at the end for polite requests." },
    vocab: [["hätte gern", "would like"], ["könnte", "could"], ["würde", "would"], ["der Termin", "the appointment"]],
    prag: { scenario: "You are calling a doctor's office to ask for an appointment politely.", q: "Which is the most polite option?", opts: ["Ich will einen Termin.", "Ich hätte gern einen Termin.", "Gib mir einen Termin."], a: 1, note: "Konjunktiv II forms like hätte gern soften requests and sound polite." },
    write: { prompt: "Schreiben Sie eine höfliche Bitte an einen Vermieter oder ein Amt.", hint: "Use: Ich hätte gern …, Wäre … möglich?, Ich würde mich freuen, wenn …", sample: "Ich hätte gern einen Termin für nächste Woche. Wäre Mittwochnachmittag möglich? Ich würde mich über eine kurze Antwort freuen." },
  },
  {
    slug: "work-email", level: "A2", title: "At work and email etiquette", de: "Bei der Arbeit und E-Mail-Etikette", theme: "work",
    summary: "Write and understand simple, polite work emails and office conversations.",
    dlg: { title: "Im Büro", lines: [
      ["Frau Klein", "Guten Morgen, Herr Özdemir. Haben Sie den Bericht fertig?", "Good morning, Mr Özdemir. Is the report ready?"],
      ["Herr Özdemir", "Fast. Ich schicke ihn Ihnen heute Nachmittag per E-Mail.", "Almost. I'll send it to you by email this afternoon."],
      ["Frau Klein", "Super, vielen Dank für Ihre Mühe.", "Great, thank you for your effort."]],
      q: "When will Herr Özdemir send the report?", opts: ["This afternoon", "Tomorrow morning", "Next week"], a: 0,
      note: "per E-Mail schicken is the standard phrase for sending something electronically." },
    read: { title: "Eine E-Mail an den Chef", de: "Sehr geehrte Frau Bauer, ich möchte Ihnen mitteilen, dass ich am Freitag einen Arzttermin habe. Ich werde daher etwas später ins Büro kommen. Mit freundlichen Grüßen, Elif Yildiz.",
      en: "Dear Ms Bauer, I would like to inform you that I have a doctor's appointment on Friday. I will therefore come to the office a bit later. Best regards, Elif Yildiz.",
      q: "Why will Elif come later on Friday?", opts: ["A doctor's appointment", "A meeting", "Traffic"], a: 0,
      note: "Sehr geehrte/r and Mit freundlichen Grüßen are formal email conventions." },
    pron: { de: "Mit freundlichen Grüßen", en: "Best regards (formal closing)", stress: "mit FREUND-li-chen GRÜ-ßen", tip: "The ß in Grüßen is pronounced like a sharp s." },
    blanks: [
      { s: "___ geehrter Herr Meier, vielen Dank für Ihre Nachricht.", en: "Dear Mr Meier, thank you for your message.", opts: ["Sehr", "Liebe", "Hallo"], a: 0, note: "Sehr geehrter Herr … is the standard formal salutation." },
      { s: "Ich schicke Ihnen den Bericht ___ E-Mail.", en: "I am sending you the report by email.", opts: ["mit", "per", "in"], a: 1, note: "per E-Mail is the fixed phrase for sending by email." }],
    order: { answer: ["Ich", "melde", "mich", "morgen", "wieder", "bei", "Ihnen"], en: "I will get back to you tomorrow.", note: "sich bei jemandem melden means to get in touch with someone." },
    vocab: [["der Bericht", "the report"], ["die Nachricht", "the message"], ["die Besprechung", "the meeting"], ["mitteilen", "to inform"]],
    prag: { scenario: "You need to call in sick to your workplace formally.", q: "What is the most appropriate opening?", opts: ["Hey, ich komme heute nicht.", "Sehr geehrte Frau Schulz, ich muss Ihnen leider mitteilen, dass ich heute krank bin.", "Ich bin krank, tschüss."], a: 1, note: "Formal work communication requires polite phrasing and a formal salutation." },
    write: { prompt: "Schreiben Sie eine kurze formelle E-Mail an Ihren Chef über einen freien Tag.", hint: "Use: Sehr geehrte/r …, ich möchte Ihnen mitteilen, dass …, Mit freundlichen Grüßen.", sample: "Sehr geehrte Frau Hoffmann, ich möchte Ihnen mitteilen, dass ich am Montag einen wichtigen Termin habe. Ich werde daher einen Tag Urlaub nehmen. Mit freundlichen Grüßen, Marco Rossi." },
  },
  {
    slug: "appointments-bureaucracy", level: "A2", title: "Appointments and bureaucracy", de: "Termine und Behördengänge", theme: "daily-life",
    summary: "Make appointments and handle basic bureaucracy at German offices.",
    dlg: { title: "Beim Bürgeramt", lines: [
      ["Beamtin", "Guten Tag, haben Sie einen Termin?", "Hello, do you have an appointment?"],
      ["Herr Weber", "Ja, um zehn Uhr, für die Anmeldung.", "Yes, at ten o'clock, for registration."],
      ["Beamtin", "Haben Sie Ihren Ausweis und die Unterlagen dabei?", "Do you have your ID and documents with you?"],
      ["Herr Weber", "Ja, hier bitte.", "Yes, here you go."]],
      q: "What is Herr Weber's appointment for?", opts: ["Registration", "A passport", "A visa"], a: 0,
      note: "die Anmeldung is required registration when you move to a new address in Germany." },
    read: { title: "Ein Termin beim Amt", de: "Ich musste einen Termin beim Einwohnermeldeamt vereinbaren. Ich brauchte meinen Ausweis und eine Bestätigung vom Vermieter. Der Termin dauerte nur zehn Minuten.",
      en: "I had to make an appointment at the residents' registration office. I needed my ID and a confirmation from the landlord. The appointment only took ten minutes.",
      q: "What did the writer need from the landlord?", opts: ["A confirmation", "A key", "A contract"], a: 0,
      note: "einen Termin vereinbaren is the standard phrase for booking an appointment." },
    pron: { de: "Ich brauche einen Termin.", en: "I need an appointment.", stress: "ich BRAU-che EI-nen ter-MIN", tip: "Termin is stressed on the last syllable, unlike English 'term'." },
    blanks: [
      { s: "Ich möchte einen Termin ___.", en: "I would like to make an appointment.", opts: ["vereinbaren", "verlieren", "verstehen"], a: 0, note: "einen Termin vereinbaren means to make an appointment." },
      { s: "Bringen Sie bitte Ihren ___ mit.", en: "Please bring your ID with you.", opts: ["Ausweis", "Auskunft", "Anmeldung"], a: 0, note: "der Ausweis is the identity card required at offices." }],
    order: { answer: ["Ich", "muss", "mich", "beim", "Amt", "anmelden"], en: "I have to register at the office.", note: "sich anmelden is a separable reflexive verb; the prefix an- goes to the end." },
    vocab: [["der Termin", "the appointment"], ["die Anmeldung", "the registration"], ["der Ausweis", "the ID card"], ["die Unterlagen", "the documents"]],
    prag: { scenario: "You arrive at an office and need to explain you have a booked appointment.", q: "What do you say?", opts: ["Ich habe einen Termin um elf Uhr.", "Ich will jetzt rein.", "Termin, schnell!"], a: 0, note: "State your appointment time clearly and politely." },
    write: { prompt: "Beschreiben Sie einen Behördengang, den Sie hatten oder haben müssen.", hint: "Use: Ich musste einen Termin vereinbaren, ich brauchte …, der Termin dauerte …", sample: "Ich musste einen Termin beim Bürgeramt vereinbaren, weil ich umgezogen bin. Ich brauchte meinen Ausweis und eine Bestätigung vom Vermieter. Der Termin dauerte nur fünfzehn Minuten." },
  },
  {
    slug: "renting-flat", level: "A2", title: "Renting a flat", de: "Eine Wohnung mieten", theme: "housing",
    summary: "Discuss viewing and renting a flat with a landlord or agent.",
    dlg: { title: "Wohnungsbesichtigung", lines: [
      ["Vermieterin", "Die Wohnung hat zwei Zimmer und eine kleine Küche.", "The flat has two rooms and a small kitchen."],
      ["Frau Ahmadi", "Wie hoch ist die Kaltmiete?", "How much is the base rent?"],
      ["Vermieterin", "Sechshundert Euro, plus Nebenkosten.", "Six hundred euros, plus additional costs."],
      ["Frau Ahmadi", "Und ab wann ist sie frei?", "And from when is it available?"]],
      q: "What is the Kaltmiete for the flat?", opts: ["600 euros", "700 euros", "500 euros"], a: 0,
      note: "die Kaltmiete is the base rent without utilities; Nebenkosten are extra costs." },
    read: { title: "Meine neue Wohnung", de: "Ich habe endlich eine Wohnung gefunden. Sie kostet vierhundertfünfzig Euro Kaltmiete plus Nebenkosten. Ich musste eine Kaution von zwei Monatsmieten bezahlen.",
      en: "I finally found a flat. It costs four hundred fifty euros base rent plus additional costs. I had to pay a deposit of two months' rent.",
      q: "How much deposit did the writer pay?", opts: ["Two months' rent", "One month's rent", "No deposit"], a: 0,
      note: "die Kaution is a security deposit, usually two to three months' rent." },
    pron: { de: "Wie hoch ist die Miete?", en: "How much is the rent?", stress: "wie HOCH ist die MIE-te", tip: "The ie in Miete is a long i sound." },
    blanks: [
      { s: "Die ___ kostet sechshundert Euro im Monat.", en: "The (base) rent costs six hundred euros a month.", opts: ["Kaltmiete", "Kaution", "Anmeldung"], a: 0, note: "die Kaltmiete refers to rent without utility costs." },
      { s: "Ich muss eine ___ von zwei Monatsmieten zahlen.", en: "I have to pay a deposit of two months' rent.", opts: ["Kaution", "Miete", "Nebenkosten"], a: 0, note: "die Kaution is the security deposit paid before moving in." }],
    order: { answer: ["Die", "Wohnung", "ist", "ab", "Januar", "frei"], en: "The flat is available from January.", note: "ab + month indicates the starting availability date." },
    vocab: [["die Miete", "the rent"], ["die Kaution", "the deposit"], ["die Nebenkosten", "the additional costs"], ["der Vermieter", "the landlord"]],
    prag: { scenario: "You are viewing a flat and want to ask when it becomes available.", q: "What do you ask?", opts: ["Ab wann ist die Wohnung frei?", "Wie ist die Wohnung frei?", "Wann Wohnung frei?"], a: 0, note: "Ab wann ist … frei? is the natural way to ask about availability." },
    write: { prompt: "Beschreiben Sie eine Wohnung, die Sie mieten möchten.", hint: "Use: Die Wohnung hat …, Die Kaltmiete beträgt …, Ich brauche eine Kaution von …", sample: "Die Wohnung hat drei Zimmer und einen Balkon. Die Kaltmiete beträgt siebenhundert Euro plus Nebenkosten. Ich muss eine Kaution von zwei Monatsmieten bezahlen." },
  },
  {
    slug: "banking-money", level: "A2", title: "Banking and money", de: "Bank und Geld", theme: "daily-life",
    summary: "Open a bank account and handle basic banking vocabulary.",
    dlg: { title: "Ein Konto eröffnen", lines: [
      ["Bankberater", "Möchten Sie ein Girokonto eröffnen?", "Would you like to open a checking account?"],
      ["Frau Sato", "Ja, ich brauche es für mein Gehalt.", "Yes, I need it for my salary."],
      ["Bankberater", "Haben Sie Ihren Ausweis und eine Meldebescheinigung?", "Do you have your ID and a registration certificate?"],
      ["Frau Sato", "Ja, hier bitte.", "Yes, here you go."]],
      q: "Why does Frau Sato want a bank account?", opts: ["For her salary", "For savings only", "For a loan"], a: 0,
      note: "ein Girokonto is the standard everyday checking account in Germany." },
    read: { title: "Meine Bank", de: "Ich habe ein Konto bei einer Onlinebank. Meine Miete wird automatisch abgebucht. Wenn ich Geld brauche, hebe ich es am Automaten ab.",
      en: "I have an account with an online bank. My rent is automatically debited. When I need money, I withdraw it at the ATM.",
      q: "How does the writer pay rent?", opts: ["Automatic debit", "Cash", "Cheque"], a: 0,
      note: "abbuchen means to debit automatically; abheben means to withdraw cash." },
    pron: { de: "Ich möchte Geld abheben.", en: "I would like to withdraw money.", stress: "ich MÖCH-te GELD AB-he-ben", tip: "abheben is a separable verb; ab- is stressed." },
    blanks: [
      { s: "Ich möchte ein Konto ___.", en: "I would like to open an account.", opts: ["eröffnen", "abheben", "bezahlen"], a: 0, note: "ein Konto eröffnen means to open an account." },
      { s: "Meine Miete wird automatisch ___.", en: "My rent is automatically debited.", opts: ["abgehoben", "abgebucht", "abgeschickt"], a: 1, note: "abgebucht (from abbuchen) means automatically deducted." }],
    order: { answer: ["Ich", "hebe", "Geld", "am", "Automaten", "ab"], en: "I am withdrawing money at the ATM.", note: "The separable prefix ab- from abheben goes to the end." },
    vocab: [["das Konto", "the account"], ["abheben", "to withdraw"], ["überweisen", "to transfer"], ["das Gehalt", "the salary"]],
    prag: { scenario: "You need to ask a bank employee about opening an account.", q: "What is the appropriate question?", opts: ["Ich will ein Konto, sofort.", "Könnten Sie mir helfen, ein Konto zu eröffnen?", "Konto jetzt!"], a: 1, note: "A polite question with Könnten Sie mir helfen is appropriate at a bank." },
    write: { prompt: "Beschreiben Sie, wie Sie mit Geld und Bank umgehen.", hint: "Use: Ich habe ein Konto bei …, Ich überweise …, Ich hebe Geld ab, wenn …", sample: "Ich habe ein Konto bei einer großen Bank. Ich überweise meine Miete jeden Monat automatisch. Wenn ich Bargeld brauche, hebe ich es am Automaten ab." },
  },
  {
    slug: "describing-people", level: "A2", title: "Describing people and character", de: "Personen und Charakter beschreiben", theme: "people",
    summary: "Describe appearance and personality traits of people you know.",
    dlg: { title: "Wie ist dein neuer Kollege?", lines: [
      ["Rosa", "Wie ist dein neuer Kollege?", "What is your new colleague like?"],
      ["Felix", "Er ist sehr freundlich und hilfsbereit.", "He is very friendly and helpful."],
      ["Rosa", "Und wie sieht er aus?", "And what does he look like?"],
      ["Felix", "Er ist groß und hat kurze, braune Haare.", "He is tall and has short, brown hair."]],
      q: "What is the new colleague's personality like?", opts: ["Friendly and helpful", "Shy and quiet", "Rude"], a: 0,
      note: "aussehen describes appearance; character adjectives describe personality." },
    read: { title: "Meine beste Freundin", de: "Meine beste Freundin heißt Clara. Sie ist klein und schlank und hat lockige Haare. Sie ist sehr geduldig und immer ehrlich zu mir.",
      en: "My best friend is called Clara. She is small and slim and has curly hair. She is very patient and always honest with me.",
      q: "What kind of hair does Clara have?", opts: ["Curly", "Straight", "Short"], a: 0,
      note: "lockig means curly; ehrlich and geduldig describe character traits." },
    pron: { de: "Er ist sehr hilfsbereit.", en: "He is very helpful.", stress: "er ist sehr HILFS-be-reit", tip: "Hilfsbereit is a compound word stressed on Hilfs-." },
    blanks: [
      { s: "Sie hat lange, ___ Haare.", en: "She has long, blond hair.", opts: ["blonde", "blond", "blonder"], a: 0, note: "Adjectives before a plural noun take the -e ending: blonde Haare." },
      { s: "Mein Bruder ist sehr ___.", en: "My brother is very honest.", opts: ["ehrlich", "ehrliche", "ehrlichen"], a: 0, note: "After sein, adjectives take no ending." }],
    order: { answer: ["Meine", "Schwester", "ist", "klein", "und", "sehr", "lustig"], en: "My sister is small and very funny.", note: "Adjectives after sein describe the subject without endings." },
    vocab: [["freundlich", "friendly"], ["geduldig", "patient"], ["ehrlich", "honest"], ["schlank", "slim"]],
    prag: { scenario: "A friend asks you to describe someone you met at a party.", q: "Which is a natural description?", opts: ["Er ist nett und sehr witzig.", "Er nett witzig ist.", "Nett er ist."], a: 0, note: "Simple sentence order: subject, verb, adjectives." },
    write: { prompt: "Beschreiben Sie eine Person, die Sie gut kennen.", hint: "Use: … ist …, … hat …, … sieht … aus.", sample: "Mein bester Freund heißt Tom. Er ist groß und hat kurze, dunkle Haare. Er ist sehr lustig und immer hilfsbereit." },
  },
  {
    slug: "telling-story", level: "A2", title: "Telling a story", de: "Eine Geschichte erzählen", theme: "narrative",
    summary: "Narrate a simple past event using connectors like zuerst, dann and danach.",
    dlg: { title: "Was ist passiert?", lines: [
      ["Nora", "Was ist gestern passiert?", "What happened yesterday?"],
      ["Tobias", "Zuerst habe ich verschlafen. Dann habe ich den Bus verpasst.", "First I overslept. Then I missed the bus."],
      ["Nora", "Oje! Und danach?", "Oh no! And after that?"],
      ["Tobias", "Danach bin ich mit dem Taxi zur Arbeit gefahren.", "After that I went to work by taxi."]],
      q: "How did Tobias get to work in the end?", opts: ["By taxi", "By bus", "On foot"], a: 0,
      note: "zuerst, dann and danach help order events in a story." },
    read: { title: "Ein verrückter Tag", de: "Zuerst klingelte mein Wecker nicht. Dann fand ich meine Schlüssel nicht. Schließlich kam ich eine Stunde zu spät zur Arbeit.",
      en: "First my alarm clock did not ring. Then I could not find my keys. Finally I arrived an hour late for work.",
      q: "What was the final result of the story?", opts: ["Arriving late to work", "Missing a meeting", "Losing the keys forever"], a: 0,
      note: "schließlich signals the final event in a sequence of a story." },
    pron: { de: "Zuerst, dann, danach, schließlich.", en: "First, then, after that, finally.", stress: "tsu-ERST, DANN, da-NACH, SCHLIESS-lich", tip: "These connectors are common signposts in spoken narratives." },
    blanks: [
      { s: "___ bin ich aufgestanden, dann habe ich gefrühstückt.", en: "First I got up, then I had breakfast.", opts: ["Zuerst", "Schließlich", "Nie"], a: 0, note: "Zuerst introduces the first event in a sequence." },
      { s: "___ hat es geregnet, deshalb kamen wir spät an.", en: "It rained, therefore we arrived late.", opts: ["Deshalb", "Danach", "Zuerst"], a: 1, note: "Danach signals the event that follows chronologically." }],
    order: { answer: ["Zuerst", "sind", "wir", "spazieren", "gegangen"], en: "First we went for a walk.", note: "Time connector zuerst goes first, verb second." },
    vocab: [["zuerst", "first"], ["dann", "then"], ["danach", "after that"], ["schließlich", "finally"]],
    prag: { scenario: "You are telling a friend a funny story about your day and want it to flow logically.", q: "Which connectors help order the events?", opts: ["Zuerst, dann, danach, schließlich", "Vielleicht, aber, oder", "Und, oder, aber"], a: 0, note: "Sequencing words help structure a narrative clearly." },
    write: { prompt: "Erzählen Sie eine kurze Geschichte von einem besonderen Tag.", hint: "Use: Zuerst …, Dann …, Danach …, Schließlich …", sample: "Zuerst bin ich früh aufgewacht. Dann habe ich mich mit Freunden getroffen. Danach sind wir ins Kino gegangen. Schließlich haben wir zusammen zu Abend gegessen." },
  },
  {
    slug: "opinions-disagreement", level: "A2", title: "Opinions and disagreement", de: "Meinungen äußern und widersprechen", theme: "conversation",
    summary: "Express your opinion politely and disagree in a respectful way.",
    dlg: { title: "Eine Diskussion", lines: [
      ["Hakan", "Ich finde, dass Homeoffice besser ist.", "I think that working from home is better."],
      ["Ines", "Das stimmt nicht ganz. Im Büro arbeitet man produktiver.", "That's not quite true. You work more productively in the office."],
      ["Hakan", "Da bin ich anderer Meinung.", "I disagree with that."]],
      q: "What does Hakan think is better?", opts: ["Working from home", "Working in the office", "A mix of both"], a: 0,
      note: "Ich bin anderer Meinung is a polite way to disagree." },
    read: { title: "Meinungen zum Handy in der Schule", de: "Manche Leute meinen, dass Handys in der Schule verboten sein sollten. Andere finden, dass man sie zum Lernen nutzen kann. Ich persönlich glaube, dass es auf die Situation ankommt.",
      en: "Some people think that phones should be banned in school. Others think you can use them for learning. Personally, I believe it depends on the situation.",
      q: "What does the writer personally believe?", opts: ["It depends on the situation", "Phones should be banned", "Phones are always useful"], a: 0,
      note: "meinen and glauben introduce personal opinions." },
    pron: { de: "Ich bin anderer Meinung.", en: "I disagree.", stress: "ich bin AN-de-rer MEI-nung", tip: "Meinung stresses the first syllable, MEI-." },
    blanks: [
      { s: "Ich ___, dass das eine gute Idee ist.", en: "I think that this is a good idea.", opts: ["finde", "find", "findet"], a: 0, note: "ich finde is the first-person form used to give an opinion." },
      { s: "Da bin ich ___ Meinung.", en: "I am of a different opinion there.", opts: ["anderer", "anderen", "anders"], a: 0, note: "anderer Meinung sein means to disagree." }],
    order: { answer: ["Meiner", "Meinung", "nach", "ist", "das", "richtig"], en: "In my opinion, that is right.", note: "Meiner Meinung nach is a fixed phrase introducing an opinion." },
    vocab: [["die Meinung", "the opinion"], ["zustimmen", "to agree"], ["widersprechen", "to disagree"], ["meiner Meinung nach", "in my opinion"]],
    prag: { scenario: "A colleague states an opinion you strongly disagree with in a meeting.", q: "What is a polite way to disagree?", opts: ["Das ist falsch!", "Ich sehe das anders.", "Du hast keine Ahnung."], a: 1, note: "Ich sehe das anders is a softer, more polite way to disagree." },
    write: { prompt: "Äußern Sie Ihre Meinung zu einem aktuellen Thema.", hint: "Use: Ich finde, dass …, Meiner Meinung nach …, Ich bin anderer Meinung, weil …", sample: "Ich finde, dass Homeoffice viele Vorteile hat. Meiner Meinung nach spart man Zeit und Geld. Manche sind anderer Meinung, weil ihnen der Kontakt zu Kollegen fehlt." },
  },
  {
    slug: "news-media", level: "A2", title: "News and media", de: "Nachrichten und Medien", theme: "media",
    summary: "Talk about how you follow the news and different media sources.",
    dlg: { title: "Wie informierst du dich?", lines: [
      ["Petra", "Wie informierst du dich über Nachrichten?", "How do you keep up with the news?"],
      ["Ali", "Ich lese meistens eine Nachrichten-App.", "I mostly read a news app."],
      ["Petra", "Ich schaue lieber die Tagesschau im Fernsehen.", "I prefer to watch the Tagesschau on TV."]],
      q: "How does Ali follow the news?", opts: ["Via a news app", "Newspaper", "Radio"], a: 0,
      note: "sich informieren über means to keep informed about something." },
    read: { title: "Nachrichten heute", de: "Früher haben die Menschen nur Zeitung gelesen. Heute nutzen viele das Internet und soziale Medien. Manche vertrauen den Nachrichten im Internet nicht so sehr.",
      en: "In the past people only read newspapers. Today many use the internet and social media. Some do not trust the news on the internet as much.",
      q: "What did people mainly use in the past?", opts: ["Newspapers", "Radio", "Television"], a: 0,
      note: "vertrauen + dative expresses trust: den Nachrichten vertrauen." },
    pron: { de: "Ich lese die Nachrichten online.", en: "I read the news online.", stress: "ich LE-se die NACH-rich-ten ON-lein", tip: "Nachrichten stresses the first syllable Nach-." },
    blanks: [
      { s: "Ich ___ mich jeden Tag über die Nachrichten.", en: "I inform myself about the news every day.", opts: ["informiere", "informieren", "informiert"], a: 0, note: "sich informieren conjugates like a regular reflexive verb." },
      { s: "Viele Leute vertrauen ___ Zeitungen nicht mehr.", en: "Many people no longer trust newspapers.", opts: ["die", "den", "der"], a: 1, note: "vertrauen takes the dative: den Zeitungen." }],
    order: { answer: ["Ich", "informiere", "mich", "über", "das", "Internet"], en: "I inform myself via the internet.", note: "The reflexive pronoun mich comes right after the verb." },
    vocab: [["die Nachrichten", "the news"], ["die Zeitung", "the newspaper"], ["vertrauen", "to trust"], ["sich informieren", "to inform oneself"]],
    prag: { scenario: "A friend asks where you get reliable information from.", q: "What is a natural response?", opts: ["Ich informiere mich über seriöse Nachrichtenseiten.", "Ich lese nichts.", "Nachrichten sind langweilig."], a: 0, note: "seriös means reliable/credible, an important word when discussing media." },
    write: { prompt: "Wie informieren Sie sich über aktuelle Ereignisse?", hint: "Use: Ich informiere mich über …, Ich lese/schaue …, Ich vertraue …", sample: "Ich informiere mich meistens über eine Nachrichten-App. Am Abend schaue ich auch die Nachrichten im Fernsehen. Ich vertraue vor allem seriösen Zeitungen." },
  },
  {
    slug: "culture-traditions", level: "A2", title: "Culture and traditions", de: "Kultur und Traditionen", theme: "culture",
    summary: "Discuss German festivals and traditions and compare them with your own.",
    dlg: { title: "Weihnachtsmarkt", lines: [
      ["Yara", "Warst du schon auf dem Weihnachtsmarkt?", "Have you already been to the Christmas market?"],
      ["Finn", "Ja, ich habe Glühwein getrunken und Lebkuchen gegessen.", "Yes, I drank mulled wine and ate gingerbread."],
      ["Yara", "In meinem Land haben wir andere Traditionen zu Weihnachten.", "In my country we have other traditions for Christmas."]],
      q: "What did Finn eat at the Christmas market?", opts: ["Lebkuchen", "Bratwurst", "Kuchen"], a: 0,
      note: "der Weihnachtsmarkt is a popular German winter tradition." },
    read: { title: "Deutsche Feste", de: "In Deutschland feiert man im Oktober das Oktoberfest in München. Zu Ostern bemalen viele Familien Eier. An Weihnachten schmückt man einen Tannenbaum.",
      en: "In Germany, people celebrate the Oktoberfest in Munich in October. At Easter, many families paint eggs. At Christmas, people decorate a fir tree.",
      q: "What do people do at Easter in Germany?", opts: ["Paint eggs", "Light candles", "Bake bread"], a: 0,
      note: "bemalen means to paint/decorate something." },
    pron: { de: "Wir feiern Weihnachten zusammen.", en: "We celebrate Christmas together.", stress: "wir FEI-ern WEIH-nach-ten zu-SAM-men", tip: "The ei in feiern and Weihnachten sounds like English 'eye'." },
    blanks: [
      { s: "In Deutschland ___ man im Herbst das Oktoberfest.", en: "In Germany, people celebrate the Oktoberfest in autumn.", opts: ["feiert", "feiern", "gefeiert"], a: 0, note: "man takes the third-person singular verb form: man feiert." },
      { s: "Zu Ostern ___ viele Familien Eier.", en: "At Easter many families paint eggs.", opts: ["bemalen", "bemalt", "bemale"], a: 0, note: "viele Familien is plural, so the verb takes the plural ending -en." }],
    order: { answer: ["An", "Weihnachten", "schmücken", "wir", "einen", "Tannenbaum"], en: "At Christmas we decorate a fir tree.", note: "An Weihnachten is the fixed expression for 'at Christmas'." },
    vocab: [["das Fest", "the festival"], ["feiern", "to celebrate"], ["die Tradition", "the tradition"], ["schmücken", "to decorate"]],
    prag: { scenario: "A German friend invites you to a traditional festival and asks about your own traditions.", q: "How could you respond?", opts: ["In meinem Land feiern wir das anders.", "Ich habe keine Traditionen.", "Das interessiert mich nicht."], a: 0, note: "Sharing your own cultural traditions is a natural, friendly response." },
    write: { prompt: "Beschreiben Sie ein Fest oder eine Tradition aus Ihrem Land.", hint: "Use: Bei uns feiern wir …, Wir essen/trinken …, Diese Tradition bedeutet …", sample: "Bei uns feiern wir im Frühling ein großes Fest. Wir essen traditionelles Gebäck und treffen die ganze Familie. Diese Tradition bedeutet für uns viel." },
  },
  {
    slug: "a2-recap", level: "A2", title: "A2 recap", de: "A2 Wiederholung", theme: "review",
    summary: "Review key A2 grammar and vocabulary through everyday situations.",
    dlg: { title: "Ein Jahr in Deutschland", lines: [
      ["Lehrerin", "Wie war dein erstes Jahr in Deutschland?", "How was your first year in Germany?"],
      ["Diego", "Am Anfang war es schwer, weil ich wenig Deutsch sprach.", "At the beginning it was hard, because I spoke little German."],
      ["Lehrerin", "Und jetzt?", "And now?"],
      ["Diego", "Jetzt fühle ich mich viel sicherer und werde bald die B1-Prüfung machen.", "Now I feel much more confident and will soon take the B1 exam."]],
      q: "What will Diego do soon?", opts: ["Take the B1 exam", "Move back home", "Start university"], a: 0,
      note: "This dialogue combines Präteritum, reflexive verbs and the future with werden." },
    read: { title: "Rückblick auf mein Deutschlernen", de: "Als ich nach Deutschland kam, konnte ich nur wenige Wörter. Ich habe viel gelernt, weil ich jeden Tag geübt habe. Bald werde ich die nächste Prüfung machen, weil ich mich gut vorbereitet fühle.",
      en: "When I came to Germany, I could only speak a few words. I have learned a lot because I practised every day. Soon I will take the next exam because I feel well prepared.",
      q: "Why has the writer learned a lot?", opts: ["Practised every day", "Took a course abroad", "Watched films only"], a: 0,
      note: "This passage combines als, weil, Perfekt and the future with werden." },
    pron: { de: "Ich habe viel gelernt und fühle mich sicherer.", en: "I have learned a lot and feel more confident.", stress: "ich HA-be FIEL ge-LERNT und FÜH-le mich SI-che-rer", tip: "Practise linking clauses smoothly without pausing too much." },
    blanks: [
      { s: "Als ich ankam, ___ ich kein Deutsch.", en: "When I arrived, I spoke no German.", opts: ["sprach", "spreche", "gesprochen"], a: 0, note: "als + Präteritum describes a single past situation." },
      { s: "Ich werde die Prüfung bestehen, ___ ich viel geübt habe.", en: "I will pass the exam because I have practised a lot.", opts: ["weil", "wenn", "aber"], a: 0, note: "weil introduces the reason, with the verb at the end." }],
    order: { answer: ["Ich", "werde", "mich", "gut", "vorbereiten"], en: "I will prepare myself well.", note: "sich vorbereiten combines a reflexive verb with the future werden construction." },
    vocab: [["sich vorbereiten", "to prepare oneself"], ["die Prüfung", "the exam"], ["sicherer", "more confident/secure"], ["üben", "to practise"]],
    prag: { scenario: "A classmate asks how your German learning journey has been so far.", q: "Which response best summarises progress using A2 grammar?", opts: ["Am Anfang war es schwer, aber ich habe viel geübt und werde bald die Prüfung machen.", "Deutsch ist schwer.", "Ich weiß nicht."], a: 0, note: "A rich answer uses Präteritum, Perfekt and the future together." },
    write: { prompt: "Schreiben Sie einen kurzen Rückblick auf Ihr Deutschlernen mit verschiedenen Zeitformen.", hint: "Use: Als ich anfing, …; Ich habe …; Jetzt werde ich …", sample: "Als ich anfing, Deutsch zu lernen, konnte ich nur wenige Sätze. Ich habe viel geübt und mit anderen Lernenden gesprochen. Jetzt fühle ich mich sicherer und werde bald die B1-Prüfung machen." },
  },
];
