import type { LessonSeed } from "./types";

export const FOUNDATION: LessonSeed[] = [
  {
    slug: "alphabet-a-m", level: "A0", title: "The Alphabet A–M", de: "Das Alphabet A–M", theme: "foundation",
    summary: "Say the first half of the German alphabet and spell your name out loud.",
    dlg: { title: "Wie schreibt man das?", lines: [
      ["Beamtin", "Wie heißen Sie, bitte?", "What is your name, please?"],
      ["Herr Baum", "Ich heiße Baum. B wie Berta, A, U, M.", "My name is Baum. B as in Berta, A, U, M."],
      ["Beamtin", "Buchstabieren Sie bitte Ihren Vornamen.", "Please spell your first name."],
      ["Herr Baum", "J-A-K-O-B. Jakob.", "J-A-K-O-B. Jakob."]],
      q: "What is the man asked to do?", opts: ["Spell his first name", "Repeat his address", "Show his passport"], a: 0,
      note: "buchstabieren means to spell. Germans often say B wie Berta to make a letter clear." },
    read: { title: "Die ersten Buchstaben", de: "Das deutsche Alphabet hat sechsundzwanzig Buchstaben. A, B, C, D, E, F, G, H, I, J, K, L und M sind die ersten dreizehn. Das J spricht man wie das englische y, und das C hört man meistens nur in Kombinationen wie ch.",
      en: "The German alphabet has twenty-six letters. A, B, C, D, E, F, G, H, I, J, K, L and M are the first thirteen. J sounds like the English y, and C is mostly heard only in combinations such as ch.",
      q: "How many letters does the German alphabet have?", opts: ["Twenty-four", "Twenty-six", "Thirty"], a: 1,
      note: "Letter names differ from English: E sounds like ay, I sounds like ee." },
    pron: { de: "A, B, C, D, E, F, G", en: "A, B, C, D, E, F, G", stress: "AH BEH TSEH DEH EH EFF GEH", tip: "C is tseh and G is geh with a hard g, never a j sound." },
    blanks: [
      { s: "Wie ___ man das?", en: "How do you spell that?", opts: ["schreibt", "spricht", "liest"], a: 0, note: "Wie schreibt man das? is the standard way to ask for a spelling." },
      { s: "Der Buchstabe J klingt wie das englische ___.", en: "The letter J sounds like the English y.", opts: ["j", "y", "g"], a: 1, note: "German J = English y, as in ja and Jakob." }],
    order: { answer: ["Können", "Sie", "das", "bitte", "buchstabieren"], en: "Could you spell that, please?", note: "In a question the verb comes first and the infinitive goes to the end." },
    vocab: [["A", "ah"], ["B", "beh"], ["C", "tseh"], ["D", "deh"], ["E", "eh"], ["F", "eff"], ["G", "geh"], ["H", "hah"], ["I", "ee"], ["J", "yot"], ["K", "kah"], ["L", "ell"], ["M", "emm"]],
    prag: { scenario: "Someone says a name too quickly on the phone.", q: "What do you say?", opts: ["Was?", "Können Sie das bitte buchstabieren?", "Sprechen Sie lauter!"], a: 1, note: "Asking politely for a spelling is the normal move on the phone." },
    write: { prompt: "Buchstabieren Sie Ihren Namen auf Deutsch.", hint: "Use: Ich heiße …, Das schreibt man …", sample: "Ich heiße Anna. Das schreibt man A-N-N-A. Mein Nachname ist Klein: K-L-E-I-N." },
  },
  {
    slug: "alphabet-n-z", level: "A0", title: "The Alphabet N–Z & Umlauts", de: "Das Alphabet N–Z & Umlaute", theme: "foundation",
    summary: "Finish the alphabet and meet Ä, Ö, Ü and ß.",
    dlg: { title: "Am Telefon", lines: [
      ["Mitarbeiter", "Und Ihr Nachname?", "And your surname?"],
      ["Frau Groß", "Groß. G-R-O-ß, das scharfe S.", "Groß. G-R-O-ß, the sharp S."],
      ["Mitarbeiter", "Mit Eszett, alles klar. Und die Straße?", "With eszett, understood. And the street?"],
      ["Frau Groß", "Königsweg, mit Ö.", "Königsweg, with Ö."]],
      q: "Which special letter is in her surname?", opts: ["Ü", "ß", "Ä"], a: 1,
      note: "ß is called Eszett or scharfes S and is always pronounced like a sharp s." },
    read: { title: "Der Rest des Alphabets", de: "Nach dem M kommen N, O, P, Q, R, S, T, U, V, W, X, Y und Z. Dazu gibt es vier Sonderzeichen: Ä, Ö, Ü und ß. Das V klingt wie f, das W wie ein englisches v und das Z wie ts.",
      en: "After M come N, O, P, Q, R, S, T, U, V, W, X, Y and Z. There are also four special characters: Ä, Ö, Ü and ß. V sounds like f, W like an English v and Z like ts.",
      q: "How does the German W sound?", opts: ["Like English w", "Like English v", "Like f"], a: 1,
      note: "V and W swap places compared with English: Vater = fahter, Wasser = vasser." },
    pron: { de: "V, W, X, Y, Z", en: "V, W, X, Y, Z", stress: "fau VEH ix IPP-si-lon TSETT", tip: "Z is always tsett, never a buzzing z." },
    blanks: [
      { s: "Mein Name ist Müller, mit ___.", en: "My name is Müller, with ü.", opts: ["ü", "u", "ue"], a: 0, note: "Umlauts change the sound: u is oo, ü is a rounded ee." },
      { s: "Das Wort Straße schreibt man mit ___.", en: "The word Straße is written with ß.", opts: ["ss", "ß", "s"], a: 1, note: "ß follows long vowels; ss follows short ones (Straße vs. Fluss)." }],
    order: { answer: ["Mein", "Name", "ist", "Müller", "mit", "Umlaut"], en: "My name is Müller, with an umlaut.", note: "mit Umlaut is the quick way to clarify the spelling." },
    vocab: [["N", "enn"], ["O", "oh"], ["P", "peh"], ["Q", "kuh"], ["R", "err"], ["S", "ess"], ["T", "teh"], ["U", "oo"], ["V", "fau"], ["W", "veh"], ["X", "ix"], ["Y", "ypsilon"], ["Z", "tsett"], ["Ä", "ah-umlaut"], ["Ö", "oh-umlaut"], ["Ü", "oo-umlaut"], ["ß", "eszett"]],
    prag: { scenario: "A clerk writes your name without the umlaut.", q: "How do you correct it politely?", opts: ["Falsch!", "Entschuldigung, das ist mit Umlaut: ü.", "Nochmal schreiben."], a: 1, note: "Start with Entschuldigung and give the exact letter." },
    write: { prompt: "Schreiben Sie drei Wörter mit Ä, Ö oder Ü.", hint: "Use: Das Wort … schreibt man mit …", sample: "Das Wort Käse schreibt man mit ä. Der Löffel hat ein ö. Die Tür schreibt man mit ü." },
  },
  {
    slug: "sounds-and-spelling", level: "A0", title: "Sounds & Spelling Rules", de: "Laute & Rechtschreibung", theme: "foundation",
    summary: "Learn the letter combinations that make German easy to read aloud.",
    dlg: { title: "Wie spricht man das?", lines: [
      ["Lernerin", "Wie spricht man ie und ei?", "How do you pronounce ie and ei?"],
      ["Lehrer", "Sie sprechen den zweiten Buchstaben: ie ist ii, ei ist ai.", "You say the second letter: ie is ee, ei is eye."],
      ["Lernerin", "Also heißt wie 'vee' und mein 'main'?", "So wie is 'vee' and mein is 'mine'?"],
      ["Lehrer", "Genau, sehr gut!", "Exactly, very good!"]],
      q: "How is the combination ei pronounced?", opts: ["Like ee", "Like eye", "Like ay"], a: 1,
      note: "Say the name of the second vowel: ei = eye, ie = ee." },
    read: { title: "Fünf Regeln", de: "Sch klingt wie sh in Schule. Ch nach a, o, u ist rau wie in Buch. St und sp am Wortanfang klingen wie scht und schp: Straße, sprechen. Das r hinten im Hals ist typisch deutsch, und ein e am Wortende bleibt immer hörbar.",
      en: "Sch sounds like sh in Schule. Ch after a, o, u is rough as in Buch. St and sp at the start of a word sound like sht and shp: Straße, sprechen. The r comes from the back of the throat, and a final e is always audible.",
      q: "How does sp sound at the start of a word?", opts: ["Like sp in English", "Like shp", "Like ts"], a: 1,
      note: "Word-initial st and sp always get the sh sound." },
    pron: { de: "Ich spreche schon ein bisschen Deutsch.", en: "I already speak a little German.", stress: "ich SHPRE-che shohn ain BISS-chen DOITCH", tip: "spreche starts with shp; the ch in ich is soft, like a whispered h." },
    blanks: [
      { s: "Das Wort Schule beginnt mit dem Laut ___.", en: "The word Schule begins with the sh sound.", opts: ["s", "sch", "ch"], a: 1, note: "sch is one single sound, like English sh." },
      { s: "In dem Wort 'sie' spricht man das ie wie ___.", en: "In the word sie the ie is pronounced like ee.", opts: ["ee", "eye", "ay"], a: 0, note: "ie is a long ee: sie, wie, Liebe." }],
    order: { answer: ["Ich", "spreche", "langsam", "und", "deutlich"], en: "I speak slowly and clearly.", note: "The conjugated verb sits in position two in a German statement." },
    vocab: [["sch", "sh sound"], ["ch (nach a, o, u)", "rough h from the throat"], ["ei", "sounds like eye"], ["ie", "sounds like ee"], ["eu", "sounds like oy"], ["z", "sounds like ts"], ["v", "sounds like f"], ["w", "sounds like v"]],
    prag: { scenario: "You are unsure how to pronounce a word you just read.", q: "What do you ask?", opts: ["Sag das!", "Wie spricht man das aus?", "Ich verstehe nicht."], a: 1, note: "Wie spricht man das aus? asks specifically about pronunciation." },
    write: { prompt: "Nennen Sie drei Wörter mit sch, ch oder ei.", hint: "Use: Das Wort … hat …", sample: "Das Wort Schwester hat sch. Das Wort Nacht hat ch. Das Wort Wein hat ei." },
  },
  {
    slug: "numbers-0-20", level: "A0", title: "Numbers 0–20", de: "Zahlen 0–20", theme: "foundation",
    summary: "Count from zero to twenty and give your phone number.",
    dlg: { title: "Die Telefonnummer", lines: [
      ["Arzthelferin", "Wie ist Ihre Telefonnummer?", "What is your phone number?"],
      ["Patient", "Null, eins, sieben, drei, vier, zwölf.", "Zero, one, seven, three, four, twelve."],
      ["Arzthelferin", "Und wie alt sind Sie?", "And how old are you?"],
      ["Patient", "Ich bin neunzehn.", "I am nineteen."]],
      q: "How old is the patient?", opts: ["Nine", "Nineteen", "Twelve"], a: 1,
      note: "Germans often say zwo instead of zwei on the phone so it is not confused with drei." },
    read: { title: "Von null bis zwanzig", de: "null, eins, zwei, drei, vier, fünf, sechs, sieben, acht, neun, zehn. Danach: elf, zwölf, dreizehn, vierzehn, fünfzehn, sechzehn, siebzehn, achtzehn, neunzehn, zwanzig. Achtung: sechzehn und siebzehn verlieren einen Laut.",
      en: "zero, one, two, three, four, five, six, seven, eight, nine, ten. Then: eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty. Careful: sechzehn and siebzehn drop a sound.",
      q: "Which number is irregular?", opts: ["vierzehn", "sechzehn", "achtzehn"], a: 1,
      note: "sechs becomes sech- and sieben becomes sieb- before -zehn." },
    pron: { de: "eins, zwei, drei, vier, fünf", en: "one, two, three, four, five", stress: "AINS TSVAI DRAI FEER FUENF", tip: "zwei starts with ts; fünf uses the rounded ü sound." },
    blanks: [
      { s: "Nach zehn kommt ___.", en: "After ten comes eleven.", opts: ["elf", "zwölf", "zehnein"], a: 0, note: "elf and zwölf are unique words, not built from zehn." },
      { s: "Ich bin ___ Jahre alt. (16)", en: "I am sixteen years old.", opts: ["sechszehn", "sechzehn", "sechsehn"], a: 1, note: "sechzehn loses the s of sechs." }],
    order: { answer: ["Ich", "bin", "zwanzig", "Jahre", "alt"], en: "I am twenty years old.", note: "German says Jahre alt, literally years old." },
    vocab: [["null", "0"], ["eins", "1"], ["zwei", "2"], ["drei", "3"], ["vier", "4"], ["fünf", "5"], ["sechs", "6"], ["sieben", "7"], ["acht", "8"], ["neun", "9"], ["zehn", "10"], ["elf", "11"], ["zwölf", "12"], ["dreizehn", "13"], ["vierzehn", "14"], ["fünfzehn", "15"], ["sechzehn", "16"], ["siebzehn", "17"], ["achtzehn", "18"], ["neunzehn", "19"], ["zwanzig", "20"]],
    prag: { scenario: "Someone gives a phone number too fast to write down.", q: "What do you say?", opts: ["Stopp!", "Langsamer bitte, noch einmal.", "Egal."], a: 1, note: "Langsamer bitte is polite and clear." },
    write: { prompt: "Schreiben Sie Ihre Telefonnummer in Worten.", hint: "Use: Meine Nummer ist … / Ich bin … Jahre alt.", sample: "Meine Nummer ist null eins sieben drei acht zwei. Ich bin achtzehn Jahre alt." },
  },
  {
    slug: "numbers-to-100", level: "A0", title: "Tens & Numbers to 100", de: "Zehnerzahlen bis 100", theme: "foundation",
    summary: "Count in tens to one hundred and build every number in between.",
    dlg: { title: "Wie viel kostet das?", lines: [
      ["Verkäufer", "Der Rucksack kostet vierzig Euro.", "The backpack costs forty euros."],
      ["Kundin", "Und die Tasche?", "And the bag?"],
      ["Verkäufer", "Fünfundsechzig Euro.", "Sixty-five euros."],
      ["Kundin", "Dann nehme ich den Rucksack.", "Then I will take the backpack."]],
      q: "How much is the bag?", opts: ["45", "65", "56"], a: 1,
      note: "fünfundsechzig = five and sixty. German says the units first." },
    read: { title: "Die Zehner", de: "zehn, zwanzig, dreißig, vierzig, fünfzig, sechzig, siebzig, achtzig, neunzig, hundert. Zwischen den Zehnern zählt man rückwärts: einundzwanzig, zweiunddreißig, siebenundvierzig. Dreißig schreibt man mit ß, und sechzig und siebzig sind wieder kürzer.",
      en: "ten, twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety, one hundred. Between the tens you count backwards: twenty-one, thirty-two, forty-seven. dreißig is written with ß, and sechzig and siebzig are shortened again.",
      q: "How do you say 47 in German?", opts: ["vierzigsieben", "siebenundvierzig", "vierundsiebzig"], a: 1,
      note: "Unit + und + ten, written as one word." },
    pron: { de: "zwanzig, dreißig, vierzig, fünfzig, hundert", en: "twenty, thirty, forty, fifty, one hundred", stress: "TSVAN-tsich DRAI-sich FEER-tsich FUENF-tsich HUN-dert", tip: "The ending -zig sounds like -tsich in most of Germany." },
    blanks: [
      { s: "83 heißt auf Deutsch ___.", en: "83 in German is dreiundachtzig.", opts: ["achtzigdrei", "dreiundachtzig", "achtunddreizig"], a: 1, note: "Units first: drei + und + achtzig." },
      { s: "30 schreibt man ___.", en: "30 is written dreißig.", opts: ["dreizig", "dreißig", "dreiszig"], a: 1, note: "dreißig is the only ten with ß instead of z." }],
    order: { answer: ["Das", "kostet", "fünfundsiebzig", "Euro"], en: "That costs seventy-five euros.", note: "Prices follow the verb: Das kostet + amount + Euro." },
    vocab: [["zehn", "10"], ["zwanzig", "20"], ["dreißig", "30"], ["vierzig", "40"], ["fünfzig", "50"], ["sechzig", "60"], ["siebzig", "70"], ["achtzig", "80"], ["neunzig", "90"], ["hundert", "100"], ["einundzwanzig", "21"], ["zweiunddreißig", "32"], ["siebenundvierzig", "47"], ["neunundneunzig", "99"]],
    prag: { scenario: "You want to check a price you think you misheard.", q: "What do you ask?", opts: ["Wie bitte, fünfzig oder fünfzehn?", "Zu teuer!", "Sagen Sie das nochmal."], a: 0, note: "Naming both options is the clearest way to resolve 15 vs 50." },
    write: { prompt: "Schreiben Sie drei Preise in Worten.", hint: "Use: Das kostet … Euro.", sample: "Das Buch kostet zwölf Euro. Die Jacke kostet fünfundvierzig Euro. Das Fahrrad kostet hundert Euro." },
  },
  {
    slug: "grammar-basics", level: "A0", title: "Basic Grammar Rules", de: "Grammatik-Grundlagen", theme: "foundation",
    summary: "The three articles, verb endings, pronouns and the verb-second rule.",
    dlg: { title: "Der, die oder das?", lines: [
      ["Lernerin", "Warum heißt es der Tisch, aber die Lampe?", "Why is it der Tisch but die Lampe?"],
      ["Lehrer", "Jedes Nomen hat ein Geschlecht: der, die oder das.", "Every noun has a gender: der, die or das."],
      ["Lernerin", "Und wie lerne ich das?", "And how do I learn that?"],
      ["Lehrer", "Lernen Sie das Wort immer mit dem Artikel.", "Always learn the word together with its article."]],
      q: "What advice does the teacher give?", opts: ["Learn nouns with their article", "Ignore the gender", "Only use das"], a: 0,
      note: "Nouns are always capitalised and always carry a gender." },
    read: { title: "Vier Grundregeln", de: "Erstens: Nomen schreibt man groß und sie haben der, die oder das. Zweitens: Das Verb steht im Aussagesatz an Position zwei. Drittens: Verben bekommen Endungen — ich lerne, du lernst, er lernt, wir lernen, ihr lernt, sie lernen. Viertens: Für höfliche Anrede benutzt man Sie.",
      en: "First: nouns are capitalised and take der, die or das. Second: the verb stands in position two in a statement. Third: verbs take endings — ich lerne, du lernst, er lernt, wir lernen, ihr lernt, sie lernen. Fourth: use Sie for polite address.",
      q: "Where does the verb go in a German statement?", opts: ["At the end", "In second position", "First"], a: 1,
      note: "Verb-second is the backbone of German word order." },
    pron: { de: "Der Tisch, die Lampe, das Fenster.", en: "The table, the lamp, the window.", stress: "der TISH dee LAM-pe das FEN-ster", tip: "Keep the article unstressed and stress the noun." },
    blanks: [
      { s: "___ Kind spielt im Garten.", en: "The child is playing in the garden.", opts: ["Der", "Die", "Das"], a: 2, note: "Kind is neuter: das Kind." },
      { s: "Du ___ sehr schnell.", en: "You learn very quickly.", opts: ["lerne", "lernst", "lernt"], a: 1, note: "The du form ends in -st." }],
    order: { answer: ["Heute", "lerne", "ich", "Deutsch"], en: "Today I am learning German.", note: "When a time word comes first, the verb still stays in position two and the subject follows it." },
    vocab: [["der", "the (masculine)"], ["die", "the (feminine / plural)"], ["das", "the (neuter)"], ["ich", "I"], ["du", "you (informal)"], ["er / sie / es", "he / she / it"], ["wir", "we"], ["ihr", "you (plural)"], ["sie / Sie", "they / you (polite)"], ["das Nomen", "the noun"], ["das Verb", "the verb"]],
    prag: { scenario: "You are speaking to an older stranger in a shop.", q: "Which form do you use?", opts: ["Wie heißt du?", "Wie heißen Sie?", "Wie heißt ihr?"], a: 1, note: "Sie is the respectful form with strangers and in formal settings." },
    write: { prompt: "Schreiben Sie drei Sätze über sich mit dem Verb an Position zwei.", hint: "Use: Ich heiße …, Ich lerne …, Heute …", sample: "Ich heiße Sofia. Ich lerne seit einem Monat Deutsch. Heute übe ich das Alphabet und die Zahlen." },
  },
];
